feat: check for sast/snyk code setting on org before running code test
snyk/cli pull request #1921
Opened 2021-05-17 07:34 UTC by neonnoon

#### What does this PR do?

Fixes [COD-123](https://snyksec.atlassian.net/browse/COD-123).

This PR prevents snyk code analysis unless enabled for the orgaization.

#### How to test?

Run `snyk code test` for an organization that does not have it enabled.

```
snyk code test --org=testorg
Snyk Code is not supported for org testorg.
```

2021-05-17 08:08 UTC, neonnoon commented
Smoke test fails because org `snyk-cli-smoke-test-with-snykcode` does not have snyk code enabled, looking into it...

2021-05-17 15:13 UTC, Spoor2709 requested changes
Great Job! 2 small comments to resolve 😃

2021-05-17 15:13 UTC, Spoor2709 commented on src/lib/settings.ts
> +import request = require('./request');
Required: Since this file is SAST specific it needs to live in the src/lib/plugins/sast folder

2021-05-17 15:13 UTC, Spoor2709 commented on src/lib/plugins/sast/validate.ts
> +  if (sastSettingsResponse.code === 401 || sastSettingsResponse.code === 403) {
Question: should we handle other error codes such as a 500?

2021-05-17 16:14 UTC, neonnoon commented on src/lib/plugins/sast/validate.ts
> +  if (sastSettingsResponse.code === 401 || sastSettingsResponse.code === 403) {
Good question! From the previous (feature flag based) implementation I assumed that we do not need/want to show a specific error. Do you think it's necessary?

From a functionality point of view, any error will cause snyk code analysis to be skipped, which is correct IMHO.

2021-05-17 16:16 UTC, neonnoon commented on src/lib/settings.ts
> +import request = require('./request');
Depends whether we see this as a general place for (org/cli) setting checks to be implemented, or sast-specific, I guess?

2021-05-17 16:25 UTC, neonnoon commented
As smoke test runs towards app.snyk.io, this can only be merged & released once https://github.com/snyk/registry/pull/20845 is released to prod.

2021-05-20 11:36 UTC, Spoor2709 commented on src/lib/settings.ts
> +import request = require('./request');
When I read this file I see it as very sast specific logic the cli should have as little notion as possible of sast

2021-05-20 11:37 UTC, Spoor2709 commented on src/lib/plugins/sast/validate.ts
> +  if (sastSettingsResponse.code === 401 || sastSettingsResponse.code === 403) {
This is a very good question. I think you are right here 😃

2021-05-21 15:38 UTC, Spoor2709 approved these changes
Great Job! LGTM!

2021-05-21 16:20 UTC, jahed-snyk approved these changes

2021-05-21 16:27 UTC, merged