[NEB-10] feat: track, check and enforce test limit on cli
snyk/cli pull request #2019
Opened 2021-06-11 10:06 UTC by neonnoon

- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ ] tests still missing

#### What does this PR do?

- validates if 
- adds test 

#### Screenshots

```
❯ snyk code test
Test limit reached!

You have reached your monthly limit of 2 private tests for your org.
To learn more about our plans and increase your tests limit visit https://snyk.io/plans.
You have reached your monthly limit of 24 code tests for your org.
To learn more about our plans and increase your tests limit visit https://snyk.io/plans.
```

2021-06-23 13:20 UTC, miiila commented on src/lib/plugins/sast/checks.ts
> +    url: `${config.API}/track-sast-usage/cli`,
`question`: is `track-sast-usage` route implemented in registry? Just curious if it is safe to start calling it :-)

2021-06-23 13:20 UTC, miiila approved these changes

2021-06-23 15:10 UTC, neonnoon commented on src/lib/plugins/sast/checks.ts
> +    url: `${config.API}/track-sast-usage/cli`,
Yes, see https://github.com/snyk/registry/pull/21469

2021-06-25 12:27 UTC, JackuB commented on src/lib/plugins/sast/checks.ts
> +      Authorization: `token ${snyk.api}`,
I think using a getter is safer here. It's defined in `api-token.ts` 

```suggestion
      Authorization: `token ${getApiToken()}`,
```

2021-06-25 12:29 UTC, JackuB approved these changes

2021-06-25 12:29 UTC, JackuB commented
Commit message could mention this affects only sast

2021-06-25 12:39 UTC, jahed-snyk requested changes

2021-06-25 12:39 UTC, jahed-snyk commented on test/jest/unit/snyk-code-test.spec.ts
> +      await cli.test('some/path', { code: true });
This will pass if `cli.test` does not throw. You should use something like:

```ts
await expect(cli.test('some/path', { code: true }))
  .rejects.toHaveProperty('userMessage', 'Test limit reached!')
```

2021-06-25 12:39 UTC, jahed-snyk commented on src/lib/plugins/sast/checks.ts
> +  return (response as any).body;
Why do you need `as any` here? Can we make this type-safe? It looks like this response only has `userMessage` and `code` so it should not be difficult to parse.

Also it looks like you're not handling HTTP response codes (if the request fails) which will lead to an ambigious error. Maybe on non-ok status codes, there should be a fallback response with a user-friendly `userMessage`?

2021-06-25 12:39 UTC, jahed-snyk commented on src/lib/plugins/sast/validate.ts
> +      trackUsageResponse.userMessage,
`trackUsageResponse` is a `TrackUsageResponse` type, but `TrackUsageResponse` does not have a `userMessage`. Should we define it? Where is it coming from?

2021-06-25 12:39 UTC, jahed-snyk commented on src/lib/plugins/sast/checks.ts
> +  error?: string;
This `error` is not used anywhere by the looks of it. Did you mean `userMessage`?

2021-06-25 12:46 UTC, JackuB commented on src/lib/plugins/sast/checks.ts
> +  return (response as any).body;
Wouldn't it be better to make this fail silently? It's only checking for the status code 429?

2021-06-25 13:02 UTC, jahed-snyk commented on src/lib/plugins/sast/checks.ts
> +  return (response as any).body;
@JackuB I guess if the `body` is validated and falls back to a predefined body (whether that's an okay or a different failure, I'll leave that to SAST team to decide), it should handle any potential server issues. Something like:

```ts
try {
  return getTrackUsageResponse(response) // validate `code` and `userMessage` types
} catch (e) {
  debug(e)
  return okayTrackingUsageResponse
}
```

My main concern here is that `body` is not being validated so it can potentially be anything which defeats the point of using TypeScript.

2021-06-29 06:44 UTC, neonnoon commented on test/jest/unit/snyk-code-test.spec.ts
> +      await cli.test('some/path', { code: true });
Good point, fixed my new test and previous ones with the same issue.

2021-06-29 07:16 UTC, neonnoon commented on src/lib/plugins/sast/checks.ts
> +  return (response as any).body;
There's (at least 😛 ) two problems here:
- we had a weird cyclic import for the api token which required! us to use require and thus we didn't have types -> fixed
- some of the types were incorrect (because not properly checked) -> fixed

What remains is because `request.ts` doesn't use generics we still need to assert the reponse type here, right?

2021-06-29 07:17 UTC, neonnoon commented on src/lib/plugins/sast/validate.ts
> +      trackUsageResponse.userMessage,
Fixed

2021-06-29 09:42 UTC, jahed-snyk commented on src/lib/plugins/sast/checks.ts
> +  return (response as any).body;
Yes, but you can make it typesafe instead of using `any`. This might need a larger discussion (we use `any` a lot in places) so I won't block on this.

2021-06-29 09:42 UTC, jahed-snyk approved these changes

2021-06-30 06:53 UTC, merged