feat: update issue representation in CLI output
snyk/cli pull request #2039
Opened 2021-06-17 11:55 UTC by andygongea

Fixed the green misusage
Updated text
Reduce repetition for package upgrade

- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots

#### Additional questions

2021-07-02 12:46 UTC, jahed-snyk approved these changes, later dismissed

2021-07-04 12:11 UTC, JackuB requested changes

2021-07-08 13:40 UTC, jahed-snyk commented on src/lib/theme.ts
> +const noColor = (text: string): string => text;
Using defaults now.

2021-09-15 06:56 UTC, pkey commented
@andygongea Is this still relevant? 🤔

2021-09-15 07:04 UTC, andygongea commented
> @andygongea Is this still relevant? 🤔

Partially.

The formatting still needs to be updated, but when I made these changes, there were some issues with the tests. 
In the meantime, some of the colors have been updated.

2022-04-12 12:07 UTC, closed without merging