fix: handle container no image name provided [CAP-228]
snyk/cli pull request #2042
Opened 2021-06-18 15:26 UTC by iuliams

#### Missed Anything?
- [ ] Tests updated/written

#### What does this PR do?
This PR does the following:
* checks if the `container test` and `container monitor` commands receive an argument (the container image name) that shall be analysed;
* handles the errors returned by the scanning functions of the test and monitor commands

#### How should this be manually tested?
Old:
```
$ snyk container test
{"type":"Buffer","data":[]}
```
New:
```
$ snyk container test
The 'container' command can only be used if an image is specified.
```
and the same for the `monitor` command.

2021-06-21 07:20 UTC, danielle-snyk commented
@iuliams How about changing the text to be more aligned with OSS scan? 
for example: 
`Could not detect an image to ${command}. Specify an image name to scan and try running the command again.
`
So when running snyk container test the output will be 
`Could not detect an image to test. Specify an image name to scan and try running the command again.`

2021-06-21 16:14 UTC, iuliams commented on src/cli/commands/test/index.ts
> +    if (options.docker) {
Ok, this is meant to fix the following corner case:
$ snyk container test /image
Since 'container test' not handled as the other commands that use the `ecosystem` [library](https://github.com/snyk/snyk/tree/master/src/lib/ecosystems), I decided to approach it in this manner as I'm not sure how big the change is otherwise on the 'docker-plugin' side. @RotemS please let me know your thoughts and if you see a nicer way to do this.

2021-06-21 16:14 UTC, iuliams commented on src/cli/commands/test/index.ts
>    summariseErrorResults,
Added this as a separate commit as it may have to be re-iterated.

2021-06-21 16:15 UTC, iuliams commented on src/lib/ecosystems/monitor.ts
> +      throw new InternalServerError("Scanning failed. Please make sure you are using the right parameters. If the issue still persists, please contact snyk support.");
this is meant to fix e.g the following corner case (image name starting with '/'):
$ snyk container monitor /image

2021-06-21 16:32 UTC, iuliams commented on src/cli/commands/test/index.ts
> +    if (options.docker) {
Hm actually, I just noticed that by simply using the ecosystem lib with the inner checks, this seems to scan the image correctly...:
```
--- a/src/lib/ecosystems/index.ts
+++ b/src/lib/ecosystems/index.ts
@@ -20,6 +20,9 @@ export function getEcosystemForTest(options: Options): Ecosystem | null {
   if (options.code) {
     return 'code';
   }
+  if (options.docker) {
+    return 'docker';
+  }
   return null;
 }
```

2021-06-29 10:08 UTC, jahed-snyk requested changes, later dismissed
Need to update tests but other than that looks good.

2021-06-29 10:08 UTC, jahed-snyk commented on src/lib/errors/missing-arg-error.ts
> +    const msg = `Could not detect an image to ${command}. Specify an image name to scan and try running the command again.`;
Not blocking on this one:

It looks like we only need `method`/`command` to generate this message. Do we really need `method`? I think given the context of what the user ran, we can just say:

```
$ snyk test --docker
Could not detect an image. Specify an image name to scan and try running the command again.
```

This also avoids having to change method signatures for `processCommandArgs` and expose the concept of a "method" to it.

2021-06-29 10:12 UTC, jahed-snyk commented on src/lib/ecosystems/monitor.ts
> +      }
Do we have test coverage for this? We did we stop throwing `error`?

2021-07-02 10:22 UTC, iuliams commented on src/cli/commands/monitor/index.ts
Add comment why we have to do this.

2021-07-02 10:23 UTC, iuliams commented on src/lib/snyk-test/assemble-payloads.ts
> +    } else if (
-> if

2021-07-02 10:33 UTC, jahed-snyk reviewed
I've left some comments. None of them are blocking this except the comment about Project Envelope. I don't have enough context on that so I'll see if someone else from the team can review my review.

2021-07-02 10:33 UTC, jahed-snyk commented on src/cli/commands/process-command-args.ts
>    }
Should we combine into a single `if` statement?

2021-07-02 10:33 UTC, jahed-snyk commented on src/lib/snyk-test/assemble-payloads.ts
> +    } else if (
Don't need the `else` here as previous statement is throwing. Might make it more readable as independant `if` statements.

2021-07-02 10:33 UTC, jahed-snyk commented on test/process-command-args.spec.ts
> +  it('should return expected options & paths when path is undefined and is a container run', () => {
Would be nice if these test cases were phrased with the expected result rather than just saying "expected" e.g. "should return no paths when running a container scan with no path"

2021-07-02 10:33 UTC, jahed-snyk commented on src/cli/commands/test/index.ts
> +  }
It looks like this `test` function is trying to be Ecosystem agnostic (other than IAC) as part of Project Envelope IIRC. Should this statement be in `snyk-docker-plugin` (which is executed via `testEcosystem`)?

2021-07-02 11:07 UTC, iuliams commented on src/cli/commands/test/index.ts
> +  }
Yes, totally agree and tried to make my way around it, but unfortunately for this specific check I cannot see another way because the docker plugin scan() is not even called, since there is no 'path' argument that it has to scan.
Let me know if you find the approach and added comment explanation ok for this scenario.

2021-07-02 11:10 UTC, iuliams commented on src/cli/commands/test/index.ts
> +  }
See e.g for monitoring:
https://github.com/snyk/snyk/blob/master/src/lib/ecosystems/monitor.ts#L41
Path is empty -> no plugin scan() -> with the current implementation it cannot be done in snyk-docker-plugin.
One idea would be to implement an extra validation plugin handler, but this would probably be another issue.

2021-07-02 11:17 UTC, jahed-snyk approved these changes

2021-07-02 11:25 UTC, jahed-snyk commented on src/cli/commands/test/index.ts
> +  }
That makes sense. I've approved this PR 👍

I agree, seems we're missing an ecosystem validation step or we're making too many assumptions around the concept of "paths". Something to improve on in the future.

2021-07-02 11:49 UTC, gitphill commented on src/lib/ecosystems/monitor.ts
> +        throw new DockerImageNotFoundError(path);
looks same as exception thrown above - make one predicate that tests whether this exception should be thrown?

2021-07-02 11:50 UTC, gitphill commented on src/lib/snyk-test/assemble-payloads.ts
> +    }
same as https://github.com/snyk/snyk/pull/2042/files#r662954528

2021-07-02 11:50 UTC, gitphill approved these changes

2021-07-02 13:23 UTC, agranado2k reviewed
I think it's missing the `snyk-docker-plugin` version being bumped.

2021-07-02 13:35 UTC, michael-c-snyk commented on src/lib/errors/missing-arg-error.ts
> +    const msg = `Could not detect an image. Specify an image name to scan and try running the command again.`;
Is the use of ``` deliberate here? I guess the linter is happy /shrug

2021-07-02 13:55 UTC, iuliams commented on src/lib/ecosystems/monitor.ts
> +        throw new DockerImageNotFoundError(path);
Thought about it, but then we discussed it's a bit more readable as such (without combining 4 conditions in one check). Wdyt?

2021-07-06 09:15 UTC, gitphill approved these changes

2021-07-06 10:36 UTC, orsagie approved these changes

2021-07-07 10:46 UTC, merged