fix: update of new version of snyk python plugin
snyk/cli pull request #2068
Opened 2021-07-01 10:49 UTC by tonidevine1

- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?
Updates the version of snyk python-plugin on snyk cli

#### What are the relevant tickets?

https://github.com/snyk/snyk-python-plugin/pull/154

2021-07-01 16:17 UTC, jahed-snyk requested changes

2021-07-01 16:17 UTC, jahed-snyk commented on package.json
> +    "snyk-python-plugin": "^1.19.11",
Is the caret here intentional? I suggest removing it and using exact versions as before like most of our other internal deps.

I noticed this change is a patch version but requires changing tests. If we start using caret versions here, when a breaking change is made to a minor or patch release (as seen here), everyone's PR checks in this repo will start failing due to unrelated failing tests.

2021-07-01 16:28 UTC, tonidevine1 commented on package.json
> +    "snyk-python-plugin": "^1.19.11",
Thank you! This has been changed

2021-07-01 16:29 UTC, jahed-snyk approved these changes

2021-07-01 17:47 UTC, orsagie commented on test/jest/system/snyk-test/python/snyk-test-pyproject.spec.ts
> -    describe('project does not contain poetry.lock file', () => {
Here, this should still be poetry.lock as that is what the CLI autodetects.

I expect that if there is no pyproject.toml, but there is a poetry.lock, we will attempt to scan, but return an error.

2021-07-01 17:47 UTC, orsagie commented on test/jest/system/snyk-test/python/snyk-test-pyproject.spec.ts
> -    describe('project does contain poetry.lock file', () => {
same thing about changing back to poetry.lock just in the name of the test

2021-07-01 17:53 UTC, orsagie approved these changes
Please update the test names before merging

2021-07-02 08:19 UTC, tonidevine1 commented on test/jest/system/snyk-test/python/snyk-test-pyproject.spec.ts
> -    describe('project does contain poetry.lock file', () => {
Done

2021-07-02 08:19 UTC, tonidevine1 commented on test/jest/system/snyk-test/python/snyk-test-pyproject.spec.ts
> -    describe('project does not contain poetry.lock file', () => {
Done

2021-07-02 09:06 UTC, merged