test: migrate error-format test to jest
snyk/cli pull request #2076
Opened 2021-07-08 09:38 UTC by Avishagp

See title

2021-07-08 11:14 UTC, jahed-snyk requested changes
Needs some fixes.

2021-07-08 11:14 UTC, jahed-snyk commented on test/jest/acceptance/error-format.spec.ts
> +    .toBeTruthy;
Avoid calculating assertions ourselves, we should use Jest where possible.

```
expect(abridgeErrorMessage('hello there', 10).length).toBeLessThan(10)
```

2021-07-08 11:14 UTC, jahed-snyk commented on test/jest/acceptance/error-format.spec.ts
> +jest.setTimeout(1000 * 60);
We shouldn't need this for these tests

2021-07-08 11:14 UTC, jahed-snyk commented on test/jest/acceptance/error-format.spec.ts
> +import { abridgeErrorMessage } from '../../../src/lib/error-format';
This test is a unit test so we should put it under `/test/jest/unit/lib/error-format.spec.ts`

2021-07-08 12:20 UTC, Avishagp commented on test/jest/acceptance/error-format.spec.ts
> +import { abridgeErrorMessage } from '../../../src/lib/error-format';
Oops, got it mixed up. Thanks

2021-07-08 12:42 UTC, jahed-snyk commented on test/jest/acceptance/error-format.spec.ts
> +import { abridgeErrorMessage } from '../../../src/lib/error-format';
@Avishagp you missed the `/lib/`

2021-07-08 14:18 UTC, Avishagp commented on test/jest/acceptance/error-format.spec.ts
> +import { abridgeErrorMessage } from '../../../src/lib/error-format';
Why lib?

2021-07-08 15:27 UTC, jahed-snyk commented on test/jest/acceptance/error-format.spec.ts
> +import { abridgeErrorMessage } from '../../../src/lib/error-format';
The file under test is under `/src/lib/`

2021-07-12 11:19 UTC, jahed-snyk approved these changes

2021-07-13 13:19 UTC, merged