refactor: replace cc parser with split functions
snyk/cli pull request #2167
Opened 2021-08-16 08:38 UTC by almog27

- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?
This PR updates the version of the `cloud-config-parser` dependency to use a newer version that takes care of a performance issue.
Instead of calculating the treeMap for each line in the file, we are calculating the treeMap once for each file, and sending it to the parser to get the correct line number.
Therefore, for a file that has multiple issues, we only calculate the treeMap once.

#### Where should the reviewer start?

#### How should this be manually tested?
1. Download the new branch and install dependencies
2. Run `snyk iac test` with `--json` or `--sarif` flags.
3. See the line number returns in the response

#### What are the relevant tickets?
Jira Ticket [CC-1021](https://snyksec.atlassian.net/browse/CC-1021)

#### Snapshots
<img width="1070" alt="Screen Shot 2021-08-16 at 11 37 49" src="https://user-images.githubusercontent.com/1466549/129535667-bd1e1baa-8b52-4abd-9a4e-f23ea7dc94cf.png">

2021-08-16 08:48 UTC, aron commented on src/cli/commands/test/iac-local-execution/results-formatter.ts
> +  );
Apologies for the drive by comment, unless performance is significantly affected, we should aim to remove this entirely now. This will avoid confusion should we want to add the line numbers to the other output types in future.

2021-08-16 11:07 UTC, ipapast reviewed
Looks good. Tests are breaking though, you will need to update the mocking

2021-08-16 13:56 UTC, teodora-sandu requested changes
Looks good, I asked for a few small changes

2021-08-16 13:56 UTC, teodora-sandu commented on src/cli/commands/test/iac-local-execution/extract-line-number.ts
> +export function getFileTypeForLineNumber(
nit: This is the first time I've looked at this code and this function name confused me a bit. if you're up for it, could you please rename it to something like `getFileTypeForParser`?

2021-08-16 13:56 UTC, teodora-sandu commented on src/cli/commands/test/iac-local-execution/results-formatter.ts
> -    const flagsRequiringLineNumber = [
Why did we remove these checks? I think we added these checks here so we don't unnecessarily make line number calls and increase the running time

2021-08-16 13:56 UTC, teodora-sandu commented on test/jest/unit/iac-unit-tests/results-formatter.spec.ts
> +describe('tests', () => {
This test name is not very helpful - can we move the inner `it` to the `formatScanResults` `describe` and also move the `jest.clearAllMocks();` line from all tests to an `afterEach`?

2021-08-16 13:56 UTC, teodora-sandu commented on src/cli/commands/test/iac-local-execution/extract-line-number.ts
> +import { MapsDocIdToTree } from '@snyk/cloud-config-parser/dist/types';
I see this import is used in `registry` too, but can we export `MapsDocIdToTree` from https://github.com/snyk/cloud-config-parser/blob/master/lib/index.ts and change these imports in a future PR?

2021-08-16 16:50 UTC, ipapast commented on test/jest/unit/iac-unit-tests/results-formatter.spec.ts
> +describe('tests', () => {
hey @teodora-sandu, we paired a bit with Almog to check the tests and this was a commit for me to see when Almog had to disconnect for a bit. Apologies :D The state of the tests now should be good.

2021-08-16 16:54 UTC, almog27 commented on src/cli/commands/test/iac-local-execution/results-formatter.ts
> -    const flagsRequiringLineNumber = [
@teodora-sandu please see @aron's comment - https://github.com/snyk/snyk/pull/2167#discussion_r689351195

2021-08-16 16:57 UTC, almog27 commented on src/cli/commands/test/iac-local-execution/results-formatter.ts
> -    const flagsRequiringLineNumber = [
And there was some performance issue due to the fact that we were doing the whole calculation every time - this PR change this behaviour - so the big calculation happens only once, and the small calculations happen for every issue detected.
And that way, we can also support line number for the remain cases if wanted in the future to present it, and not only for JSON/SARIF

2021-08-17 08:14 UTC, teodora-sandu approved these changes

2021-08-17 08:15 UTC, almog27 commented on src/cli/commands/test/iac-local-execution/extract-line-number.ts
> +import { MapsDocIdToTree } from '@snyk/cloud-config-parser/dist/types';
Fixed - will later create fix for this at Registry too

2021-08-17 09:34 UTC, almog27 commented on package.json
> +    "@types/jest": "^27.0.1",
This dependency was updated due to failure in regression tests due to the fact that the `jest` dependency is a newer version than the types

2021-08-17 12:24 UTC, JackuB approved these changes

2021-08-17 12:28 UTC, merged