feat: exclude files/folders
snyk/cli pull request #2233
Opened 2021-09-07 17:14 UTC by Arvi3d

- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?

Bumped @snyk/code-client dependency version to 4.2.1, that provides support for new feature of excluding folders and files

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots

#### Additional questions

2021-09-07 17:39 UTC, JackuB requested changes

2021-09-07 17:39 UTC, JackuB commented on package.json
> +    "@snyk/code-client": "4.2.1",
This needs to be updated in the package-lock as well

I’m surprised the build worked 🤔

2021-09-07 18:06 UTC, Arvi3d commented on package.json
> +    "@snyk/code-client": "4.2.1",
done, updated lock file as well

2021-09-07 18:13 UTC, JackuB commented
<img width="762" alt="Screen Shot 2021-09-07 at 20 10 42" src="https://user-images.githubusercontent.com/1788727/132391430-845ce05a-cf8e-46bd-8b2b-f3a975261f19.png">

Somehow all "resolved" and "integrity" fields were removed by this change? Could you try it again? I think npm version could be the cause here - could you use npm@7?

2021-09-07 18:19 UTC, jahed-snyk commented on package.json
> +    "@snyk/code-client": "4.2.1",
If you rollback and just run (on npm 7) `npm install --save @snyk/code-client@4.2.1` you should get a proper minimal package-lock change. Should be similar to:

```
$ git diff --stat package-lock.json
 package-lock.json | 108 ++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------------------------
 1 file changed, 48 insertions(+), 60 deletions(-)
```

2021-09-07 19:58 UTC, Arvi3d commented on package.json
> +    "@snyk/code-client": "4.2.1",
done

2021-09-08 09:08 UTC, JackuB commented
<img width="993" alt="Screen Shot 2021-09-08 at 10 59 06" src="https://user-images.githubusercontent.com/1788727/132479562-072a1751-bc05-4096-803a-4eb81a6c1fe1.png">

Seems like this caused some regression in the CLI. Maybe we should improve the coverage in this repo as well

2021-09-08 11:50 UTC, Arvi3d commented
all seems fine now. please review

2021-09-08 11:50 UTC, Arvi3d commented
> <img alt="Screen Shot 2021-09-08 at 10 59 06" width="993" src="https://user-images.githubusercontent.com/1788727/132479562-072a1751-bc05-4096-803a-4eb81a6c1fe1.png">
> 
> Seems like this caused some regression in the CLI. Maybe we should improve the coverage in this repo as well

fixed, please review

2021-09-08 11:50 UTC, Arvi3d commented on package.json
> +    "@snyk/code-client": "4.2.1",
please review. all fixed now

2021-09-08 13:47 UTC, JackuB approved these changes

2021-09-08 13:54 UTC, merged