feat: add --gradle-accept-legacy-config-roles flag
snyk/cli pull request #2329
Opened 2021-10-28 12:44 UTC by muscar

- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?

This patch adds the `--gradle-accept-legacy-config-roles` flag, and uses a version of the Gradle plugin that accepts it. When set by the user, the plugin will use a more permissive dependency resolution process.

See https://github.com/snyk/snyk-gradle-plugin/pull/191/files for more details.

2021-10-28 14:11 UTC, anthogez reviewed
Why not `--gradle-support-all-config-roles`?

2021-10-29 09:44 UTC, dtrunley-snyk approved these changes

2021-10-29 11:29 UTC, ghost submitted a review, later dismissed
package-lock.json is out of sync and the diff is huge. You'll need to rollback and run `npm ci` before adding your package.json changes. Also to avoid weird bugs, best to use the latest npm@7 (if you're not already).

2021-10-29 11:32 UTC, JackuB requested changes

2021-10-29 11:32 UTC, orsagie approved these changes

2021-10-29 11:36 UTC, JackuB approved these changes
Anything we should test on the CLI side or is the gradle-plugin testing enough in this case?

2021-10-29 12:05 UTC, dekelund approved these changes

2021-10-29 12:15 UTC, merged