[CFG-1525] add drift test subcommand
snyk/cli pull request #2731
Opened 2022-02-07 08:22 UTC by sundowndev

- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?

Since we've [introduced a way to run driftctl through the Snyk CLI](https://github.com/snyk/snyk/pull/2634), we may now want to gather security insights out of those drifts. This PR adds a new subcommand to the existing `snyk iac drift` command, in order to perform a security analysis of drifts. It's currently possible to do `snyk iac drift scan --output plan://path/to/plan.json && snyk iac test ://path/to/plan.json`, but this method offers poor user experience and can bring confusion. Running `snyk iac drift test` is just a shorthand to perform the exact same operation.

#### Where should the reviewer start?

TBA

#### How should this be manually tested?

1. `./bin/snyk iac drift test --from='tfstate://path/to/terraform.tfstate'`

#### Any background context you want to provide?

TBA

#### What are the relevant tickets?

- https://snyksec.atlassian.net/browse/CFG-1525

#### Screenshots

TBA

2022-02-10 17:08 UTC, craigfurman requested changes
I have a few issues with the approach being taken here, and worry that it copy-pastes too much from our test flow. Let's talk and pair some time too 🙂

2022-02-10 17:08 UTC, craigfurman commented on src/lib/iac/drift-test.ts
> +    const scannedFiles = await scanFiles(parsedPlan);
It looks line we're duplicating a lot of the iac-test (and generic test) logic in this file. That makes me a bit uncomfortable.

Currently, the snyk-test command handler uses the psuedo-boolean-flag "mode" `iac` to fork the actual test logic here: https://github.com/snyk/snyk/blob/cdce752d18176ec3dabfc5986104bb2e395c9493/src/cli/commands/test/index.ts#L107-L112

That `iacTest` function then goes into our module iac-local-execution.

Back in the snyk-test handler, after we have results, there is some formatting logic that itself frequently forks logic based on that "mode" pseudo-boolean.

Back to this PR: this file appears to copy substantial orchestration logic both from the iac-local-execution module, and the snyk-test command handler formatting parts. Can we consider refactoring to remove the need for all that? Ideally this whole function would look something like (very pseudo-code):

```
const results = iacTest(driftAsTerraformPlan);
return toTestCommandResult(results);
```

Basically, we know we can't literally call https://github.com/snyk/snyk/blob/master/src/cli/commands/test/iac-local-execution/index.ts#L50, because that takes a path as an input - so let's try extracting another function that takes some already-parsed object, e.g. this "terraform plan", and returns scan results. That will act as a forcing function to understand all implications of what happens inside that flow too - for example, what should the analytics payload look like? The terraform-plan-esque data structure we pass in should have such metadata that when we send CLI analytics, it isn't actually counted as a terraform plan, but as drift that was tested.

Similarly, this hypothetical toTestCommandResult could be extracted from inside https://github.com/snyk/snyk/blob/master/src/cli/commands/test/index.ts.

2022-02-10 17:08 UTC, craigfurman commented on src/lib/iac/drift.ts
> +    }
There's something odd-smelling about this if-else. Why not refactor this function to pass in the options object that includes stdio, and leave the `child.stdout?.on` calls to the caller, by returning the process object. The drift-scan use case doesn't have to call it at all, as it is meaningless with inherited stdio file descriptors, and we can grab the output we need in the drift-test use case.

2022-02-11 09:59 UTC, wbeuil commented on src/cli/commands/drift.ts
> +    throw new Error(result.stderr);
I'm pretty sure than when we're using `json` or `plan` (which is simple the Terraform JSON Plan output) format flags, we simply don't print anything in stdout/stderr other than just the resources JSON format/error message if one. I maybe wrong, I'm gonna ask/check with someone else.

driftctl's exit code is not making any distinction between "there are drifts" and "there was an error", hence my approach to stderr.

2022-02-11 10:28 UTC, wbeuil commented on src/cli/commands/drift.ts
> +    return testDrifts(result.stdout, options, iacOrgSettings);
From my test, I've got:

```
several issues = 1
no issues = 0
error (not valid JSON terraform plan structure) = 0 (it just ignores and go into checking for vulns which there are not)
```

Good catch!

2022-02-11 10:33 UTC, wbeuil commented on src/cli/commands/drift.ts
> +  process.exit(result.returnCode);
As I said above, driftctl will only exit with 1 if drifts/errors and 0 if no issues, so indeed there may be something we should do. Bear in mind that this is the same behaviour than the version already merged.

2022-02-11 10:34 UTC, wbeuil commented on src/cli/commands/drift.ts
> +import { testDrifts } from '../../lib/iac/drift-test';
ahahah ok I'm good with that, will change it to `testDrift`

2022-02-11 10:59 UTC, craigfurman commented on src/cli/commands/drift.ts
> +    throw new Error(result.stderr);
Coupling to the fact that driftctl doesn't currently print anything to stderr on success is really brittle though, e.g. if we choose to change that. stderr doesn't actually have a defined purpose (https://man7.org/linux/man-pages/man3/stderr.3.html), and despite its name, it's traditionally used for diagnostic information (that you might not want to pipe on the same channel as stdout) just as often as "errors only".

> driftctl's exit code is not making any distinction between "there are drifts" and "there was an error", hence my approach to stderr

This makes using driftctl in a script reliably very awkward. This is what exit codes are for, and IMO we'd want to fix this for its own sake, even if it didn't also make this particular PR's feature easier to write 😉

2022-02-11 11:07 UTC, wbeuil commented on src/cli/commands/drift.ts
> +    throw new Error(result.stderr);
@eliecharra @moadibfr @sundowndev your thoughts on this?

2022-02-11 14:32 UTC, wbeuil commented on src/lib/iac/drift.ts
> +    }
I maybe misunderstood something in your question, but what about returning in the promise launch function the exit code and/or eventual errors?

I totally agree on passing options and probably all the args in the parent function so that only one call of the `child_process.spawn` exists, but for the `child.stdout?.on` I don't think it's worth extracting it somewhere else. The docs says that `If the child was spawned with stdio[1] set to anything other than 'pipe', then this will be null.`, thus with typescript `?` it won't be called at all. Anyway I'm more than happy to change it if you really want it.

What I have in mind right now:

```typescript
export async function driftctl(
  args: string[],
  isTestSubCommand: boolean,
): Promise<DriftCTLResult> {
  // ...

  if (isTestSubCommand) {
    args.shift();
    return launch(path, ['scan', ...args], { stdio: 'pipe' });
  }

  return launch(path, args, { stdio: 'inherit' });
}

async function launch(
  path: string,
  args: string[],
  options: child_process.SpawnOptions,
): Promise<DriftCTLResult> {
  return new Promise<DriftCTLResult>((resolve, reject) => {
    const child = child_process.spawn(path, args, options);

    let output = '';
    child.stdout?.on('data', function(data) {
      output += data.toString();
    });

    let err = '';
    child.stderr?.on('data', function(data) {
      err += data.toString();
    });

    // ....
  });
}
```

2022-02-11 16:29 UTC, moadibfr commented on src/cli/commands/drift.ts
> +    throw new Error(result.stderr);
I think it would be better to check return code but exclude the specific code of "drifted resource". But still the actual error text would be captured in stderr for now.

2022-02-14 09:24 UTC, craigfurman commented on src/lib/iac/drift.ts
> +    }
It's hard for me to be more specific without actually writing the code, so ultimately I'll defer to you rather than pick nits 😅, but basically the approach I'm recommending is:

1. inline this launch function - I'm not sure we're getting value from this particular indirection over the child_process API, as all the if-statements indicate
2. use the child_process API directly, in 2 places. For `drift scan`, we'll be forwarding stdio and propagating the exit code. For `drift test`, we're capturing the output and doing logic on the exit code (related to other threads above). These are 2 very different use cases.
3. When we have working code, take a look for improvements that might be made by refactoring. Maybe there will be room to extract a process-manipulation function in this area, maybe there won't be.

2022-02-14 12:17 UTC, sundowndev commented on src/cli/commands/drift.ts
> +    throw new Error(result.stderr);
I agree with @craigfurman that dedicated exit codes should be used to enhance this integration.

2024-01-03 12:56 UTC, closed without merging