Enable is-iac-drift analytics to be sent to registry
snyk/cli pull request #2837
Opened 2022-03-08 15:04 UTC by wbeuil

- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?

This PR enables the `snyk iac describe|gen-driftignore` to send a simple `is-iac-drift` analytics to registry.

I also changed the way we exit the process after running driftctl. Before we were just `process.exit` but that prevented us from using the builtin `analytics.addDataAndSend` function already written for us. Now we're just using the `process.exitCode` that changes only the exit code that will be returned without exiting the process. Best of both world. I added a test about our drift exit code as well.

#### Where should the reviewer start?

`src/cli/commands/describe.ts`

#### How should this be manually tested?

```
$ snyk iac describe
```

#### What are the relevant tickets?

https://snyksec.atlassian.net/browse/CFG-1647

#### Screenshots

<img width="895" alt="image" src="https://user-images.githubusercontent.com/8110579/157263480-bec249a2-5d63-4020-bfed-433405e9aed3.png">

2022-03-10 15:52 UTC, eliecharra commented on test/fixtures/iac/drift/args-echo.sh
> +#!/bin/bash
Can you try with `/usr/bin/env` ?

2022-03-10 16:20 UTC, wbeuil commented on test/fixtures/iac/drift/args-echo.sh
> +#!/bin/bash
it works with `/usr/bin/env`, do you want me to change?

2022-03-11 10:09 UTC, eliecharra requested changes

2022-03-11 10:09 UTC, eliecharra commented on src/cli/commands/test/iac-local-execution/analytics.ts
> +export function addIacDriftAnalytics(
Is it complicated to mock the `analytics` singleton and add a test for that method to validate that we retrieve fields correctly from analytics results ?

I'm not an expert but maybe with `jest.SpyOn` ?

2022-03-11 10:24 UTC, wbeuil commented on src/cli/commands/test/iac-local-execution/analytics.ts
> +  analytics.add('iac-drift-exit-code', describe.code);
I think I don't understand your question. Isn't it the exit code of driftctl scan command which is given in the new type `DriftctlExecutionResult`?

2022-03-11 10:26 UTC, wbeuil commented on src/cli/commands/test/iac-local-execution/analytics.ts
> +export function addIacDriftAnalytics(
That should work, let me try it.

2022-03-11 10:51 UTC, wbeuil commented on src/cli/commands/test/iac-local-execution/analytics.ts
> +  );
The problem here is that we call twice the `runDriftCTL` function which means we call twice the `download` function and thus if I try to call the analytics just after the download it will have an unexpected behaviour as per the code to add to analytics:

```
default:
        if (typeof value === 'number' && typeof metadata[key] === 'number') {
          metadata[key] += value;
        } else {
          if (!Array.isArray(metadata[key])) {
            metadata[key] = [metadata[key]];
          }
          Array.isArray(value)
            ? metadata[key].push(...value)
            : metadata[key].push(value);
        }
```

Basically if the value is not array and not a number it will create the array and push into it (our boolean). And if it's a number it will just increase the value... 

<img width="320" alt="image" src="https://user-images.githubusercontent.com/8110579/157853272-4dfbfaa1-0b45-493a-99fb-2ca46bf35d9e.png">

The 0 here is because I got a cache hit.

2022-03-11 10:52 UTC, wbeuil commented on src/cli/commands/test/iac-local-execution/analytics.ts
> +  );
Or I could write a custom logic inside the add function to analytics to break on our key just like `iac-metrics` key.

<img width="521" alt="image" src="https://user-images.githubusercontent.com/8110579/157853599-8079d3fb-5bf6-41e2-a3a4-69425b2e06e7.png">

2022-03-11 14:04 UTC, eliecharra commented on src/cli/commands/test/iac-local-execution/analytics.ts
> +  );
> Basically if the value is not array and not a number it will create the array and push into it (our boolean). And if it's a number it will just increase the value...

Oh fuck ok I was not aware of that 😕 

> Or I could write a custom logic inside the add function to analytics to break on our key just like iac-metrics key.

I t can be great If we could avoid to add our own custom logic and more spaghetti there 😅

Do we have a way to check an existence of a key in our own code ?
We could do like `if !analytics.get('key') { add('key') }`

2022-03-11 14:08 UTC, eliecharra commented on src/cli/commands/test/iac-local-execution/analytics.ts
> +  analytics.add('iac-drift-exit-code', describe.code);
driftctl scan exit code will be mapped to snyk exit code, which is probably logged somewhere in a generic way (it is ?)
My question is, if we are already logging the exit code, should we need to also log driftctl cmd result here too ?

2022-03-11 15:36 UTC, wbeuil commented on src/cli/commands/test/iac-local-execution/analytics.ts
> +  );
No there is no way to check that. Only an add method from what I see in the code.

2022-03-14 10:32 UTC, eliecharra commented on src/cli/commands/test/iac-local-execution/analytics.ts
> +  analytics.add('iac-drift-exit-code', describe.code);
After investigation it seems that there is no other place where we set the exit code in a generic way, so let's keep it like this

2022-03-14 10:33 UTC, eliecharra commented on src/cli/commands/test/iac-local-execution/analytics.ts
> +  );
Maybe we can check for the first execution or not in the code that downloads driftctl so we'll be able to set those values directly from there

2022-03-14 13:47 UTC, eliecharra requested changes

2022-03-14 13:47 UTC, eliecharra commented on src/cli/commands/describe.ts
>        process.exit(describe.code);
Maybe we sould use `process.exitCode` here too ? 

Maybe it will make sense to move `analytics.add('iac-drift-exit-code', exitCode);` out from `addIacDriftAnalytics` to that current method to handle exit code properly ?

2022-03-14 13:47 UTC, eliecharra commented on src/lib/iac/drift.ts
>    if (dctl === '') {
```suggestion
  let binaryExist true;
  if (dctl === '') {
      binaryExist = false;
```

2022-03-14 13:47 UTC, eliecharra commented on test/jest/unit/lib/iac/drift.spec.ts
> +    const addAnalyticsSpy = jest.spyOn(analytics, 'add');
Is it possible to mock when we're in an acceptance tests ? It could have been great to test that other analytics outside `addIacDriftAnalytics` are also set.

2022-03-14 14:10 UTC, wbeuil commented on src/cli/commands/describe.ts
>        process.exit(describe.code);
The `process.exit` will not send analytics indeed for now.

 If we use `process.exitCode` here there's two things that we could do:

- we could `return` just after that so that it sends analytics (it won't go into handleErrors)
- we could `throw` just after that and go into handleErrors and send analytics there BUT it will also output message errors because of the design of handleErrors

2022-03-14 14:13 UTC, wbeuil commented on test/jest/unit/lib/iac/drift.spec.ts
> +    const addAnalyticsSpy = jest.spyOn(analytics, 'add');
The way the acceptance tests work don't let us mock/spy analytics calls.

2022-03-14 14:40 UTC, eliecharra commented on src/cli/commands/describe.ts
>        process.exit(describe.code);
Let's go with the throw then

2022-03-14 15:14 UTC, eliecharra approved these changes

2022-03-15 11:03 UTC, merged