`snyk iac describe` show help by default and has to be called with right flags
snyk/cli pull request #3032
Opened 2022-03-15 17:24 UTC by moadibfr

- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?
`snyk iac describe` show help by default and has to be called with right flags:
--all, --only-managed or --only-managed

#### Where should the reviewer start?
Added a way to validate flags (both exclusive and required). It calls help command to get the help markdown rendered before throwing ab error that ask to add the right flag.

#### How should this be manually tested?
`snyk iac describe --all --only-unmanaged` should throw an error asking to only use one of the flags
`snyk iac describe` should throw an error asking to add one of the required flags

2022-03-16 19:52 UTC, moadibfr commented
> Please change the ownership so open source is not required on these

@robcresswell could you be more specific ? I thought I already did that. The 2 new files I created are owned by IAC right ?

2022-03-16 19:57 UTC, robcresswell commented
🤔 weird that it still pinged me for a review

2022-03-16 19:57 UTC, robcresswell approved these changes

2022-03-17 08:14 UTC, Avishagp approved these changes

2022-03-17 12:10 UTC, eliecharra requested changes

2022-03-17 12:10 UTC, eliecharra commented on test/jest/unit/lib/iac/drift.spec.ts
> +    expect(err).toEqual(new DescribeExclusiveArgumentError());
You can use [toThrow](https://jestjs.io/docs/expect#tothrowerror) `expect(() => { someThrowingCode() }).toThrow(expectedError)`

I don't know if we can use it combined with a `.not` for testing that we do not throw

2022-03-17 12:55 UTC, eliecharra approved these changes

2022-03-17 12:58 UTC, merged