chore: Wrap new CLI output with `iacCliOutput` feature flag
snyk/cli pull request #3077
Opened 2022-03-29 13:27 UTC by ofekatr

- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots

#### Additional questions

2022-03-30 11:43 UTC, ofekatr commented on src/cli/commands/test/index.ts
> +    await Promise.all(
The change in this file only entails updating the calls for the `displayResult` function to use `await`.

2022-03-30 12:12 UTC, francescomari requested changes

2022-03-30 12:12 UTC, francescomari commented on src/cli/commands/test/index.ts
> +          await displayResult(
IIUC this function will eventually check if the feature flag is active and dispatch to a different function for actually displaying the output. If that's true, this means that N results will make N HTTP calls to check for the flag. Wouldn't be more efficient to check for the feature flag once, at the beginning of the function, and create a display function depending on the status of the flag?

2022-03-30 12:12 UTC, francescomari commented on src/cli/commands/test/index.ts
> +        await getIacDisplayErrorFileOutput(reason, options),
The same comment made above for `displayResult` applies here as well, where N is the scan failures.

2022-03-30 12:14 UTC, francescomari commented on src/cli/commands/test/index.ts
> +    await Promise.all(
Incidentally, if my comments below are addressed, we might go back to have synchronous display functions, which will reduce the noise due to the switch to async functions.

2022-03-30 12:23 UTC, ofekatr commented on src/cli/commands/test/index.ts
> +          await displayResult(
This is being discussed further in [this Slack thread](https://snyk.slack.com/archives/C0127HWU0E7/p1648640919993429).

2022-03-30 12:23 UTC, ofekatr commented on src/cli/commands/test/index.ts
> +        await getIacDisplayErrorFileOutput(reason, options),
This is being discussed further in [this Slack thread](https://snyk.slack.com/archives/C0127HWU0E7/p1648640919993429).

2022-03-30 14:41 UTC, ofekatr commented on src/cli/commands/test/index.ts
> +          await displayResult(
A new implementation with the `iacCliOutput` feature flag query performed earlier in the `test` function can be found in [the latest commit](https://github.com/snyk/cli/pull/3077/commits/ef842eeab517b9cceb39f72272ccc56f1ebc6184).

In this implementation, the REST call happens only once initially.
Please let me know what you think about this version.

2022-03-30 14:41 UTC, ofekatr commented on src/cli/commands/test/index.ts
> +        await getIacDisplayErrorFileOutput(reason, options),
Discussion continues in [another comment](https://github.com/snyk/cli/pull/3077#discussion_r838628347).

2022-03-31 07:55 UTC, Avishagp approved these changes

2022-03-31 12:31 UTC, anthogez approved these changes

2022-03-31 12:31 UTC, merged