refactor: Move format and filter results to process-results
snyk/cli pull request #3080
Opened 2022-03-30 13:51 UTC by ipapast

Co-authored-by: Ofek Atar <ofek.atar@snyk.io>
Co-authored-by: Francesco Mari <francesco.mari@snyk.io>
Co-authored-by: Teodora Sandu <teodora.sandu@snyk.io>

- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots

#### Additional questions

2022-03-31 10:38 UTC, YairZ101 reviewed
Left some comment below.
All of them are basically me trying to understand why we diverged from the [suggested flow](https://miro.com/app/board/uXjVOI3jBlw=/?moveToWidget=3458764520615383560&cot=10) (not saying we shouldn't but if we are going to diverge from it I would like to understand what was the reason behind it).

2022-03-31 10:38 UTC, YairZ101 commented on src/cli/commands/test/iac-local-execution/index.ts
> +    // TODO: decide if this should go into scanFiles or stay here
Why not put it inside the `processResults` function?

2022-03-31 10:38 UTC, YairZ101 commented on src/cli/commands/test/iac-local-execution/process-results.ts
> +    ({ projectPublicIds, gitRemoteUrl } = await formatAndShareResults({
Why have we moved the `formatAndShareResults` function to here?

2022-03-31 10:38 UTC, YairZ101 commented on src/cli/commands/test/iac-local-execution/process-results.ts
> +  return filterIgnoredIssues(policy, formattedResults);
Any particular reason that the `formatScanResults` is not the last step before returning the results?

2022-04-01 10:20 UTC, teodora-sandu commented on src/cli/commands/test/iac-local-execution/process-results.ts
> +    ({ projectPublicIds, gitRemoteUrl } = await formatAndShareResults({
I think we did this temporarily. We will modify `scanFiles` to return `ScanResults` and then send those directly to `/iac-cli-share-results` (or whatever the endpoints was called). We only had an hour and wanted to keep changes as simple as we can.

2022-04-01 10:23 UTC, teodora-sandu commented on src/cli/commands/test/iac-local-execution/process-results.ts
> +  return filterIgnoredIssues(policy, formattedResults);
Do you see `filterIgnoredIssues` being in the main flow? When we created the flow we included them in `processResults`

2022-04-01 10:24 UTC, teodora-sandu commented on src/cli/commands/test/iac-local-execution/process-results/process-results.ts
> +  filteredIssues;
Should add typing

2022-04-01 10:33 UTC, teodora-sandu commented on src/cli/commands/test/iac-local-execution/index.ts
> +    // TODO: decide if this should go into scanFiles or stay here
I'm not sure. I remember trying it and then for some reason we started discussing whether it should be part of `scanFiles` or not. In the SCM import case for example (based on the Seldon work going on), these would be applied in the "scanning" phase and then the persistence of the rules (which would happen for example when the `--report` flag is used) doesn't need to care about them

So to me it made sense that this `scanFiles` function would eventually return the `ScanResults` with the actual severities

We could think about all of this though when we refactor `scanFiles` so I don't feel too strongly about it now

2022-04-03 08:57 UTC, YairZ101 commented on src/cli/commands/test/iac-local-execution/process-results.ts
> +  return filterIgnoredIssues(policy, formattedResults);
> Do you see `filterIgnoredIssues` being in the main flow? 

Not at all, let me rephrase my question above.
In the suggested flow we've said that `formatScanResults` will be the last step inside `processResults`, currently the last step is `formatScanResults`.
Is it because we've decided to change the order of the functions inside `processResults`? didn't have time to work on it and we plan to do it in the next session?

2022-04-05 08:10 UTC, francescomari commented on src/cli/commands/test/iac-local-execution/index.ts
> +    // TODO: decide if this should go into scanFiles or stay here
@YairZ101 I think there is some tension between this comment and the following about `formatAndShareResults()`. On one hand, according to the suggested flow, `applyCustomSeverities()` should be part of `processResults()`. On the other hand, `formatAndShareResults()` works on the "scan results with custom severities" and not on the plain "scan results", like the diagram suggests.

In other words, the code and the suggested flow are not compatible. Either we move `applyCustomSeverities()` to the "Scan" step, or we move `formatAndShareResults()` to the "Process Results" step. I'm personally more inclined for the second option, because sharing the results sounds like a post-scanning activity to me. What are your preferences?

2022-04-05 08:11 UTC, francescomari commented on src/cli/commands/test/iac-local-execution/process-results.ts
> +    ({ projectPublicIds, gitRemoteUrl } = await formatAndShareResults({
See [my comment](https://github.com/snyk/cli/pull/3080#discussion_r842495705) above.

2022-04-05 08:32 UTC, francescomari commented on src/cli/commands/test/iac-local-execution/process-results.ts
> +  return filterIgnoredIssues(policy, formattedResults);
We didn't have time to dig deeper in the implementation. As far as I can see, swapping the order of `formatScanResults()` and `filterIgnoredIssues()` might not be trivial. `filterIgnoredIssues()` has been written to accept an array of `FormattedResult` while, according to the suggested flow, should instead work on an array of `IacFileScanResult`. I would better leave this topic for a future session.

2022-04-05 08:38 UTC, francescomari commented on src/cli/commands/test/iac-local-execution/process-results/process-results.ts
> +  filteredIssues;
Done at cbb92e5f.

2022-04-05 15:32 UTC, francescomari commented
> Small question: do you all think we should be adding the share-results-formatters.spec.ts file in a process-results folder in test to match the src directory?

I'm not sure what's the policy here. If we had to follow the `src/` structure as closely as possible, shouldn't the directory be `test/jest/unit/cli/commands/test/iac-local-execution/process-results/`?.

2022-04-05 15:33 UTC, ipapast commented
> > Small question: do you all think we should be adding the share-results-formatters.spec.ts file in a process-results folder in test to match the src directory?
> 
> I'm not sure what's the policy here. If we had to follow the `src/` structure as closely as possible, shouldn't the directory be `test/jest/unit/cli/commands/test/iac-local-execution/process-results/`?.

true. we don't currently follow any policy I think. maybe a chat for another day

2022-04-07 09:21 UTC, teodora-sandu commented on src/cli/commands/test/iac-local-execution/index.ts
> +    // TODO: decide if this should go into scanFiles or stay here
Do we want to leave this TODO comment here? I added it but thought we would address it as part of this refactoring. If we think it's useful to leave because we'll fix it in a future PR then that's okay

2022-04-07 09:22 UTC, teodora-sandu commented on src/cli/commands/test/iac-local-execution/process-results/share-results-formatter.ts
> +import { computePaths } from '../file-utils';
Can we also move the test file `test/jest/unit/iac/share-results-formatters.spec.ts` to `test/jest/unit/iac/process-results/share-results-formatters.spec.ts`

2022-04-07 09:26 UTC, teodora-sandu commented on src/cli/commands/test/iac-local-execution/process-results/process-results.ts
> +import { formatScanResults } from '../measurable-methods';
Can we also move the import in `measure-methods` for `formatScanResults` from `./results-formatter` to `./process-results/results-formatter`. Or was there a reason why this wasn't includes in your commit @ipapast ?

If we end up moving it, could we also move the test file `test/jest/unit/iac/results-formatter.spec.ts` to `test/jest/unit/iac/process-results/results-formatter.spec.ts` and its fixture file

2022-04-07 09:27 UTC, teodora-sandu commented on src/cli/commands/test/iac-local-execution/process-results/process-results.ts
> +import { filterIgnoredIssues } from '../policy';
Does it make sense to rename this file to `index.ts` so it's clear that it's the entrypoint for this folder?

2022-04-07 09:28 UTC, teodora-sandu commented on src/cli/commands/test/iac-local-execution/process-results/process-results.ts
> +import { filterIgnoredIssues } from '../policy';
Also, why not move `src/cli/commands/test/iac-local-execution/policy.ts` to `src/cli/commands/test/iac-local-execution/process-reuslts/policy.ts` too since it's part of the "processResults` flow?

(its test file and fixture file too)

2022-04-07 09:35 UTC, teodora-sandu requested changes
Thanks for driving this, I've left some comments but let me know what you think of them!

2022-04-07 09:36 UTC, teodora-sandu commented on src/cli/commands/test/iac-local-execution/process-results/share-results-formatter.ts
> +import { computePaths } from '../file-utils';
I saw Ilianna also asked this. Although most people don't follow this rule, it's definitely strongly recommended and it will help us in the future when looking for tests

2022-04-07 10:12 UTC, francescomari commented on src/cli/commands/test/iac-local-execution/process-results/process-results.ts
> +export async function processResults(
I don't think it's worth it. All the functions used here seem to have their own unit tests, and the functionality as a whole has a lot of acceptance tests. We should be covered.

2022-04-07 10:38 UTC, francescomari commented on src/cli/commands/test/iac-local-execution/process-results/process-results.ts
> +import { filterIgnoredIssues } from '../policy';
Fixed both in one of my latest commits.

2022-04-07 10:40 UTC, francescomari commented on src/cli/commands/test/iac-local-execution/index.ts
> +    // TODO: decide if this should go into scanFiles or stay here
I agree on leaving the comment there, for the moment. The refactoring for the proposed flow is not over yet, and this will leave some direction for the future.

2022-04-07 10:40 UTC, francescomari commented on src/cli/commands/test/iac-local-execution/process-results/share-results-formatter.ts
> +import { computePaths } from '../file-utils';
Fix in one of my latest commits.

2022-04-07 11:15 UTC, teodora-sandu approved these changes
LGTM 👍

2022-04-07 12:12 UTC, merged