feat: log files over size limit [NEBULA-481]
snyk/cli pull request #3083
Opened 2022-03-31 16:20 UTC by patricia-v

#### What does this PR do?
Adds logging in debug mode to CLI to warn when files are skipped due to their size and lists which ones were skipped.
This is the CLI side where the debugging was added.

[Link to code-client side](https://github.com/snyk/code-client/pull/141)

**TODO**:
- [ ] update CLI to have the correct code-client version

#### What are the relevant tickets?
[NEBULA-481](https://snyksec.atlassian.net/browse/NEBULA-481)

#### Screenshots
![image](https://user-images.githubusercontent.com/97087926/161102824-62182367-39fe-4131-bd29-4071c7718b4a.png)

2022-03-31 19:10 UTC, metju90 commented on src/lib/plugins/sast/analysis.ts
> +import { MAX_FILE_SIZE } from '@snyk/code-client/dist/constants';
Lets export the `MAX_FILE_SIZE` in the index file [here](https://github.com/snyk/code-client/blob/95d6601732b5640a6d0b6c1c25fefe83955fad97/src/index.ts#L1).

Benefits of this:

1. If `MAX_FILE_SIZE` is in the said index file, other developers might realise that this variable is used outside the code-client repo and will make them think twice before doing a breaking change (like renaming it)
2. Usually (but not always) we import things from 'library', lets keep the industry standards unless we have a reason why not to.

2022-03-31 19:11 UTC, metju90 requested changes
Check my comment

2022-04-01 07:04 UTC, patricia-v commented on src/lib/plugins/sast/analysis.ts
> +import { MAX_FILE_SIZE } from '@snyk/code-client/dist/constants';
Since the index file is already exporting the constants [here](https://github.com/snyk/code-client/blob/95d6601732b5640a6d0b6c1c25fefe83955fad97/src/index.ts#L5), wouldn't it be enough to just add to line 1

> import { analyzeFolders, AnalysisSeverity, **_constants_** } from '@snyk/code-client';

and in line 103 add `${constants.MAX_FILE_SIZE}`? 🤔

2022-04-01 07:10 UTC, pkey commented on src/lib/plugins/sast/analysis.ts
> +import { MAX_FILE_SIZE } from '@snyk/code-client/dist/constants';
@patricia-v in my opinion, that should do, although having variables explicitly exported is nicer.

2022-04-05 07:02 UTC, metju90 approved these changes

2022-04-05 08:47 UTC, JackuB approved these changes

2022-04-05 08:47 UTC, JackuB commented on src/lib/plugins/sast/analysis.ts
> +        ]}`,
Wouldn't it be better to do a `.join(', ')` on the files array, to have a better and more predictable formatting?

2022-04-05 09:31 UTC, metju90 approved these changes

2022-04-05 09:45 UTC, merged