feat: Add an initial user message to the test output
snyk/cli pull request #3089
Opened 2022-04-04 12:02 UTC by francescomari

- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?

If the feature flag `"iacCliOutput"` is enabled and the `test` command is invoked in `iac` mode, the CLI shows an initial message to the user.

#### Where should the reviewer start?

The only change has been performed in the top-level test command (`src/cli/commands/test/index.ts`) because the initial message should be printed only once, independently on the number of tested paths.

#### How should this be manually tested?

Enable the feature flag on the Registry, and executed a `snyk iac test` command.

#### What are the relevant tickets?

[CFG-1578](https://snyksec.atlassian.net/browse/CFG-1578)

2022-04-04 12:45 UTC, YairZ101 commented on test/jest/acceptance/iac/test-output.spec.ts
> +      expect(stdout).toEqual(expect.stringContaining(initialMessage));
nit: you can write ```expect(stdout).toContain(initialMessage);``` instead.

2022-04-04 12:47 UTC, YairZ101 approved these changes
LGTM 🔥

2022-04-04 12:52 UTC, francescomari commented on test/jest/acceptance/iac/test-output.spec.ts
> +      expect(stdout).toEqual(expect.stringContaining(initialMessage));
Thanks! I fixed that at 8f1d484f.

2022-04-04 12:56 UTC, francescomari commented on src/cli/commands/test/index.ts
> +  if (shouldPrintIaCInitialMessage(options, isNewIacOutputSupported)) {
Thanks for pointing it out. Fixed at bd32436b.

2022-04-04 13:12 UTC, francescomari commented on src/cli/commands/test/index.ts
> +    options.iac && !options.json && !options.sarif && iacCliOutputFeatureFlag
Fixed at 8980248c.

2022-04-04 13:13 UTC, francescomari commented on test/jest/acceptance/iac/test-output.spec.ts
> +describe('iac test output', () => {
Fixed at 8980248c.

2022-04-04 13:14 UTC, francescomari commented
@ofekatr I've fixed the PR as you suggested and re-squashed everything in my latest commit. Thanks for your review.

2022-04-04 13:29 UTC, ofekatr commented
Thank you for applying the suggestions @francescomari.
Could I also ask that you add a screenshot of the new message to the PR's description?
It helps us analyze PR changes faster in retrospect 📟

2022-04-04 16:47 UTC, ofekatr requested changes

2022-04-04 16:47 UTC, ofekatr commented on src/cli/commands/test/index.ts
> +        chalk.bold(
I've examined the coloration of the message and got the result in the image attached below.
I think we need to add the `white` context for `chalk` here.

```suggestion
        chalk.white.bold(
```

In the image below, the top message is using the `white` context and the bottom one does not:

![image](https://user-images.githubusercontent.com/46415136/161591943-964c5f4b-f8ec-4697-8568-d9f9088a1575.png)

2022-04-05 07:20 UTC, francescomari commented on src/cli/commands/test/index.ts
> +        chalk.bold(
Fixed at f3475a97 and updated the screenshot in the description.

2022-04-05 07:54 UTC, ofekatr approved these changes

2022-04-06 13:15 UTC, jahed-snyk approved these changes
suggestion: there's a lot of IaC-specific logic in this shared `test/index.ts` module and there's not much for other teams to review. Consider refactoring IaC specific scenarios and moving logic into their own modules so that IaC can take CODEOWNER-ship of those files and reduce the need for cross-team reviews. While there may be an upfront cost to this, it will quickly pay off by reducing time-to-merge and cross-team disruption.

2022-04-07 11:11 UTC, JamesPatrickGill approved these changes

2022-04-07 11:17 UTC, merged