chore: Update test error message color [CFG-1385]
snyk/cli pull request #3218
Opened 2022-05-09 13:47 UTC by ofekatr

- [X] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots

#### Additional questions

2022-05-09 18:32 UTC, jahed-snyk requested changes
thought: Not too sure about using different colours for errors. Ideally our CLI colours for various context should be the same across products. I'll try bring relevant people into the Slack thread for thoughts. Maybe we can make IaC's red the default if it's aligned with the latest CLI branding decisions.

2022-05-09 18:32 UTC, jahed-snyk commented on src/cli/main.ts
> +        (await hasFeatureFlag('iacCliOutput', args.options));
issue: Can we avoid adding IaC-specific logic in `main`? This adds complexity into an already overloading module. As an example to avoid this: IaC can use extend `Error` with a `FormattedError` class which provides a `getFormattedMessage` for showing in CLI output with the correct colour. `legacy-error` can then use this function instead of it's available on the error object.

2022-05-10 07:35 UTC, YairZ101 approved these changes

2022-05-11 10:23 UTC, closed without merging

2022-05-11 10:23 UTC, ofekatr commented
Closed based on [this discussion](https://snyk.slack.com/archives/C0127HWU0E7/p1652109744760259)