Cfg 1886 refactor
snyk/cli pull request #3347
Opened 2022-06-21 10:56 UTC by YairZ101

- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots

#### Additional questions

2022-06-22 08:03 UTC, YairZ101 commented
> This PR renamed a unit test file to `test/jest/unit/lib/iac/test/v2/setup/local-cache/rules-bundle/rules.spec.ts`, but the equvalent file is `test/jest/unit/lib/iac/test/v2/setup/local-cache/rules-bundle/index.ts`. Can the test file name be updated?

I still need to fix this specific test so please don't focus on it yet, feel free to review all the other parts of the PR.

2022-06-22 08:22 UTC, ofekatr requested changes

2022-06-22 08:22 UTC, ofekatr commented on src/lib/iac/test/v2/setup/local-cache/rules-bundle/lookup-local.ts
> +      'User configured IaC Policy Engine executable path detected: %s',
`Policy Engine executable`

2022-06-22 08:22 UTC, ofekatr commented on src/lib/iac/test/v2/setup/local-cache/rules-bundle/lookup-local.ts
> +        'Failed to find a valid Rules Bundle in the configured path',
nit: Does Rules Bundle need to be capitalized?

2022-06-22 08:22 UTC, ofekatr commented on test/jest/unit/lib/iac/test/v2/setup/local-cache/index.spec.ts
> +import * as initRulesLib from '../../../../../../../../../src/lib/iac/test/v2/setup/local-cache/rules-bundle';
`initRulesBundleLib`

2022-06-22 08:32 UTC, ofekatr commented on src/lib/iac/test/v2/setup/local-cache/rules-bundle/index.ts
> +export async function initRules(testConfig: TestConfig): Promise<string> {
To align with the other naming conventions introduced in this refactor, it seems this function needs to be renamed to `initRulesLib`

2022-06-22 10:36 UTC, YairZ101 commented on src/lib/iac/file-utils.ts
> +  try {
AFAIK if `path` points to a non-existent file `fsPromises.stat(path)` will fail and will throw an error, that's why I added the `try` block.

2022-06-22 10:37 UTC, ofekatr commented on src/lib/iac/file-utils.ts
> +  try {
The suggestion refers only to the contents inside the try block, the catch block and its contents should stay the same

2022-06-22 10:39 UTC, YairZ101 commented on src/lib/iac/test/v2/setup/local-cache/rules-bundle/index.ts
> +  return rulesBundlePath!;
I think we've added it to this point only because we didn't add the download part, generally we shouldn't throw an error from this part of the code.

2022-06-22 10:40 UTC, ofekatr commented on src/lib/iac/file-utils.ts
> +  try {
```
  try {
    return (await fsPromises.stat(path)).isFile()
  } catch (err) {
    return false;
  }
}
```

2022-06-22 10:42 UTC, ofekatr commented on src/lib/iac/test/v2/setup/local-cache/rules-bundle/index.ts
> +  return rulesBundlePath!;
At present according to this PR downloading the rules bundle is not available yet, meaning the only way to get a rules bundle is if it's provided locally. 
By that logic, if the rules bundle is not found, the test cannot proceed as expected and so an error is thrown. 
I know we plan to add the downloading option in a follow-up PR, but we shouldn't rely on it before it's available.

2022-06-22 10:45 UTC, YairZ101 commented on src/cli/commands/test/iac/v2/index.ts
> +    userRulesBundlePath: config.IAC_BUNDLE_PATH,
I think we should keep `IAC_BUNDLE_PATH` because it is an env var that got other use cases (for local-exec) and those use cases are documented in some places that I don't want to start looking for and edit.

2022-06-22 10:48 UTC, ofekatr commented on src/cli/commands/test/iac/v2/index.ts
> +    userRulesBundlePath: config.IAC_BUNDLE_PATH,
Good point, so `IAC_BUNDLE_PATH` can be kept. 
That being said, I can confirm that this particular environment variable is currently only used for internal purposes.

2022-06-22 10:49 UTC, ofekatr commented on src/cli/commands/test/iac/v2/index.ts
> +    userRulesBundlePath: config.IAC_BUNDLE_PATH,
That being said, doesn't the fact that we're using the same environment variable as the original test flow to store rule bundles makes it problematic?

Are the rules bundles we're using for the UPE compliant with the way the rule bundles are used in the original test flow?

2022-06-22 10:51 UTC, YairZ101 commented on src/cli/commands/test/iac/v2/index.ts
> +    userRulesBundlePath: config.IAC_BUNDLE_PATH,
> Are the rules bundles we're using for the UPE compliant with the way the rule bundles are used in the original test flow?

it doesn't really matter because the user needs to choose which test flow to run.

2022-06-22 10:54 UTC, ofekatr commented on src/cli/commands/test/iac/v2/index.ts
> +    userRulesBundlePath: config.IAC_BUNDLE_PATH,
Having an environment variable that makes only one of the test flow versions available makes for a limiting usage of the CLI, and requires modifying these variables whenever switching between test flow versions. 

Ideally, switching between the 2 test flows should only depend on the two predetermined prerequisites:
- The feature flag
- The `experimental` flag

2022-06-22 10:54 UTC, YairZ101 commented on src/lib/iac/file-utils.ts
> +    tar.list({ path, sync: true, strict: true });
> If this operation can be changed to be async it'd be more preferable.

why?

2022-06-22 10:59 UTC, YairZ101 commented on src/cli/commands/test/iac/v2/index.ts
> +    userRulesBundlePath: config.IAC_BUNDLE_PATH,
> Having an environment variable that makes only one of the test flow versions available makes for a limiting usage of the CLI

I agree, that's why I'm saying we shouldn't create another env variable.
I'm not really following you suggestion in this thread, do you think we should create another env var or not?

2022-06-22 10:59 UTC, ofekatr commented on src/lib/iac/file-utils.ts
> +    tar.list({ path, sync: true, strict: true });
Since we're adding this as a utility function, we should use a versatile solution that would be useful for all the applications of this method. 
An async implementation can also be used for a sync flow.

2022-06-22 11:02 UTC, YairZ101 commented on src/lib/iac/file-utils.ts
> +    tar.list({ path, sync: true, strict: true });
> Since we're adding this as a utility function, we should use a versatile solution that would be useful for all the applications of this method.

makes more sense now that you've added this part.
I'll look what I can do.

2022-06-22 11:02 UTC, ofekatr commented on src/cli/commands/test/iac/v2/index.ts
> +    userRulesBundlePath: config.IAC_BUNDLE_PATH,
If a rules bundle made for the UPE is not compliant with the original test flow, I think we should make another env variable. 

That way, configuring a user-provided rules bundle for one of the flows becomes independent of configuring a user-provided rules bundle for the other test flow. 

That way, users can consecutively run these test flows with no need to modify their environment variables to adapt to the other test flow

2022-06-22 11:05 UTC, YairZ101 commented on src/cli/commands/test/iac/v2/index.ts
> +    userRulesBundlePath: config.IAC_BUNDLE_PATH,
I don't think we are going to get to this situation where a user is going to test both of the test flows at the same time.
please remember that the "user" in this case is us and not a regular customer, usually we will work on a specific test flow (most likely the newer one) and we will not "switch" frequently between the two, especially not to test rules bundles.

2022-06-22 11:11 UTC, YairZ101 commented on src/lib/iac/test/v2/setup/local-cache/rules-bundle/index.ts
> +  return rulesBundlePath!;
> I know we plan to add the downloading flow in a follow-up PR, but we shouldn't rely on it before it's available.

sure, because it is something temporary I'll add a random `Error`.

2022-06-22 16:20 UTC, YairZ101 commented on src/lib/iac/file-utils.ts
> +    tar.list({ path, sync: true, strict: true });
done in [d9fcd78](https://github.com/snyk/cli/pull/3347/commits/d9fcd781d3ed0ecbea13ec137678002fba5f68b8)

2022-06-22 16:21 UTC, YairZ101 commented on src/lib/iac/test/v2/setup/local-cache/rules-bundle/lookup-local.ts
> +export async function lookupLocalRulesBundle({
done in [d9fcd78](https://github.com/snyk/cli/pull/3347/commits/d9fcd781d3ed0ecbea13ec137678002fba5f68b8)

2022-06-22 16:22 UTC, YairZ101 commented on src/lib/iac/file-utils.ts
> +  try {
done in [d9fcd78](https://github.com/snyk/cli/pull/3347/commits/d9fcd781d3ed0ecbea13ec137678002fba5f68b8)

2022-06-22 16:22 UTC, YairZ101 commented on src/lib/iac/test/v2/setup/local-cache/rules-bundle/lookup-local.ts
> +      'bundle-experimental.tar.gz',
done in [d9fcd78](https://github.com/snyk/cli/pull/3347/commits/d9fcd781d3ed0ecbea13ec137678002fba5f68b8)

2022-06-22 16:22 UTC, YairZ101 commented on src/lib/iac/file-utils.ts
> +  return true;
done in [d9fcd78](https://github.com/snyk/cli/pull/3347/commits/d9fcd781d3ed0ecbea13ec137678002fba5f68b8)

2022-06-23 08:20 UTC, ofekatr commented on src/lib/iac/test/v2/setup/local-cache/rules-bundle/lookup-local.ts
> +    return (await isFile(path)) && (await isArchive(path));
nit: This arrow function can be shortened to

```
async (path: string) => (await isFile(path)) && (await isArchive(path));
```

2022-06-23 08:20 UTC, ofekatr commented on test/jest/unit/lib/iac/test/v2/setup/local-cache/rules-bundle/lookup-local.spec.ts
> +  describe('when a user configured path for a rules bundle is not provided', () => {
nit: In some locations the term rules bundle is capitalized and in some it is not. It'd be more preferable to choose one format and make all locations consistent with that naming

2022-06-23 08:20 UTC, ofekatr commented on src/lib/iac/test/v2/setup/local-cache/policy-engine/lookup-local.ts
> +  const validPolicyEngineCondition = async (path: string) => {
nit: Similar to the comment about the rules bundle's validator, can we rename this to something like `isValidPolicyEngine`?

2022-06-23 08:20 UTC, ofekatr commented on src/lib/iac/test/v2/setup/local-cache/policy-engine/lookup-local.ts
> +    return await isExe(path);
nit: This arrow function can be shortened to async (path: string) => await isExe(path);

2022-06-23 08:30 UTC, YairZ101 commented on src/lib/iac/test/v2/setup/local-cache/policy-engine/index.ts
> +    throw new Error(
done

2022-06-23 10:14 UTC, Avishagp commented on package.json
> +    "@types/tar": "^6.1.1",
Is this new dependency totally necessary? we try to limit new dependencies as much as possible

2022-06-23 10:17 UTC, YairZ101 commented on package.json
> +    "@types/tar": "^6.1.1",
it is not totally necessary but it does help developers to use the `tar` package.

2022-06-23 10:44 UTC, Avishagp commented on package.json
> +    "@types/tar": "^6.1.1",
What do you mean by it's not necessary? I wouldn't add a dependency (that also introduces a new transitive dependency) if it's not totally necessary

2022-06-23 10:55 UTC, YairZ101 commented on package.json
> +    "@types/tar": "^6.1.1",
I mean that `@types/tar` only adds type support for the `tar` package it doesn't add new functionality so technically speaking we can remove it without any problem.
I've added it because we are using the `tar` package in multiple places and adding type support for it helps in the development process.

2022-06-23 12:02 UTC, ofekatr reviewed
Added a few small comments, I'd also advise to not have duplicate tests for the local lookup logic in the wrapping functions for the UPE and rules bundle. 
Instead, I'd test the calling to the `lookupLocal` utility function, and mock the return value.

2022-06-23 12:06 UTC, YairZ101 commented on test/jest/unit/iac/file-utils.spec.ts
> +    tarSpy.mockImplementation(() => mockUntarStream);
> What lead to this change?

an error that popped up when adding the `@types/tar` package

2022-06-23 12:08 UTC, YairZ101 commented on src/lib/iac/test/v2/setup/local-cache/rules-bundle/index.ts
> +  if (rulesBundlePath) {
it doesn't really matter at this point because all of that is just a temporary code that I've added to support the Error throw that you've suggested.
I still think all of that is unnecessary because it is going to get changed in the upcoming days (hopefully today in both locations).

2022-06-24 15:54 UTC, Avishagp approved these changes

2022-06-26 08:00 UTC, ofekatr approved these changes
Excellent work on driving this through @YairZ101
Please have a look at the small comment I added around the handling of one of the errors.
All in all, LGTM 🏆

2022-06-26 08:49 UTC, YairZ101 commented on src/lib/iac/test/v2/setup/local-cache/rules-bundle/lookup-local.ts
> +      testConfig.userRulesBundlePath!, // `lookupLocal` will throw an error only if `userRulesBundlePath` is configured and invalid
Thanks for the feedback I went with your 2nd suggestion and added the new custom error that now we check for.

2022-06-26 09:08 UTC, merged