feat: container app vulns by default
snyk/cli pull request #3433
Opened 2022-07-04 09:26 UTC by yaronschwimmer

- [X] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?
Enables container app scan by default. We are introducing a new flag,
`exclude-app-vulns` in case a user would like to disable app scan.

#### How should this be manually tested?
`snyk container test <image_with_app>` should return app scan results without additional parameters.
`snyk container test --exclude-app-vulns <image_with_app>` should return only operating system scan results.

#### Any background context you want to provide?

#### What are the relevant tickets?
https://snyksec.atlassian.net/browse/MYC-56

2022-07-04 12:24 UTC, robcresswell approved these changes

2022-07-04 12:29 UTC, PeterSchafer approved these changes

2022-07-05 13:08 UTC, garethr requested changes
If we could hold on releasing this until we've talked about the internal enablement needs please.

2023-01-23 14:21 UTC, Avishagp approved these changes

2023-01-23 14:50 UTC, tommyknows commented on src/lib/formatters/test/format-test-results.ts
>    if (!options.docker || options.isDockerUser) {
I don't think that the changes to this function do what they should; as far as I can judge the optOutSuggestions are now always added (even if the customer disabled them)...

I'll have a brief look on how to improve this...

2023-01-23 15:27 UTC, tommyknows reviewed
Small nit regarding the docs suggestion.

You're currently also missing the actual changes regarding the flag; e.g. the parts in `src/cli/commands/{test,monitor}/index.ts` :)

2023-01-25 16:46 UTC, PeterSchafer approved these changes
LGTM

2023-01-25 17:02 UTC, tommyknows approved these changes
LGTM!

2023-01-25 17:11 UTC, mcombuechen approved these changes
LGTM

2023-01-25 17:22 UTC, merged