feat: add --remote-repo-url to "iac test"
snyk/cli pull request #3453
Opened 2022-07-12 11:29 UTC by francescomari

- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?

This PR adds support for the `--remote-repo-url` flag to the `iac test` command. The flag can be used by a user to override the URL of the Git repository, that is otherwise auto-detected by the command.

#### Where should the reviewer start?

Most of the logic is in `src/cli/commands/test/iac/scan.ts`. The change in this PR creates an `IacOutputMeta` object at the beginning of the scan and passes it down to the components that need the information in it. Previously, the `IacOutputMeta` was constructed by the individual components, and surfaced up the stack. Because the `IacOutputMeta` is not dependent on the paths being scanned, it can be constructed once from a combination of flag values and auto-detected information (like the name of the current working directory and the URL of the Git repository, if any).

#### How should this be manually tested?

Use different combinations of current working directory and flags:

- If the current working directory is not a Git repository `snyk iac test --report` creates a project group whose name is the name of the current working directory.
- If the current working directory is a Git repository, `snyk iac test --report` creates a project group whose name is derived from the URL of the Git repository, in the same way as the examples below.
- `snyk iac test --report --remote-repo-url=foo/bar` creates a project group whose name is `foo/bar`.
- `snyk iac test --report --remote-repo-url=https://example.com/foo/bar.git` creates a project group whose name is `foo/bar`.
- `snyk iac test --report --remote-repo-url=git@example.com:foo/bar.git` creates a project group whose name is `foo/bar`.

The summary section will always return the correct project name. For example,

```
Report Complete

  Your test results are available at: https://dev.snyk.io/org/francescomari/projects
  under the name: foo/bar
```

#### What are the relevant tickets?

[CFG-1842](https://snyksec.atlassian.net/browse/CFG-1842)

2022-07-13 12:20 UTC, ipapast approved these changes

2022-07-13 16:44 UTC, Avishagp commented on package.json
> +    "git-url-parse": "^12.0.0",
Please don't add this dependency to the CLI 🙏

2022-07-13 16:45 UTC, Avishagp requested changes
Blocking as Hammer refrains from adding new dependencies to the CLI unless totally needed. We think it's not a must here, and would prefer no new dependency is introduced

2022-07-14 08:52 UTC, ipapast commented on src/cli/commands/test/iac/index.ts
> +}
talked about it on slack, flags get one word anyway in the cli and we can't figure out when customers did something other than that. my comment was not valid

2022-07-14 12:53 UTC, merged