feat: pass projectTags arg to snyk-iac-test
snyk/cli pull request #3511
Opened 2022-08-01 15:57 UTC by ipapast

- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?

This PR passes the values of the `--project-tags` flag to the snyk-iac-test binary. You can check it in combination with this branch: https://github.com/snyk/snyk-iac-test/commit/6d8d7cc2fcb9cdb3cd4782e43810c58d398ae334 where the command accepts a new argument. For now, there is no other functionality.

I used the existing `parseTags` function in the CLI which handles the validation and errors of the `--project-tags`.

#### How should this be manually tested?

- Go to this branch: https://github.com/snyk/snyk-iac-test/tree/feat/get-project-tags-arg
- Run locally `go build -o snyk-iac-test .`
- Now on the CLI side, point to the binary you just built (and a bundle) and try it out: 

```
SNYK_IAC_POLICY_ENGINE_PATH=/Users/iliannapapastefanou/snyk-repos/snyk-iac-test/snyk-iac-test \
SNYK_IAC_BUNDLE_PATH=/Users/iliannapapastefanou/snyk-repos/opa-rules/dist.tar.gz \
snyk-dev iac test test/fixtures/iac/terraform/sg_open_ssh.tf --experimental --report --project-tags=key1=value1,key2=value2

```

#### Any background context you want to provide?
Handling the values of this command such as formatting them and adding them to the endpoint will be handled in a new PR.

#### What are the relevant tickets?
CFG-2051

2022-08-03 13:07 UTC, YairZ101 approved these changes
LGTM

2022-08-04 07:09 UTC, francescomari commented on src/lib/iac/test/v2/scan/index.ts
> +    args.push('-project-tags', JSON.stringify(options.projectTags));
`JSON.stringify()` will not generate an argument value in the same way as described in the corresponding PR in `snyk-iac-test`. Is this a leftover?

2022-08-04 07:22 UTC, ipapast commented on src/lib/iac/test/v2/scan/index.ts
> +    args.push('-project-tags', JSON.stringify(options.projectTags));
yes. just changed to `options.projectTags.toString()` instead

2022-08-04 07:38 UTC, francescomari commented on src/lib/iac/test/v2/scan/index.ts
> +    args.push('-project-tags', JSON.stringify(options.projectTags));
Does the `toString()` of the `Tag` do the right thing? A `Tag` seems to be a plain object.

2022-08-04 10:04 UTC, ipapast commented on src/lib/iac/test/v2/scan/index.ts
> +    args.push('-project-tags', JSON.stringify(options.projectTags));
Sorry, that was too fast push again 😓 
snyk-iac-test expects a string as a flag, I updated it like this:

```
if (options.projectTags) {
    const stringifiedTags = options.projectTags.map((tag) => {
      return Object.values(tag).join(':');
    });
    args.push('-project-tags', stringifiedTags.toString());
  }
```

stringifiedTags is an array of the key value pairs, eg if I run `--project-tags=key1=value1,another2=val2`, I'll get:

`[ 'key1:value1', 'another2:val2' ]`

and then `stringifiedTags.toString` will pass the  `key1:value1,another2:val2` string to the executable.

2022-08-04 11:45 UTC, francescomari requested changes

2022-08-04 11:45 UTC, francescomari commented on src/lib/iac/test/v2/scan/index.ts
> +      return Object.values(tag).join(':');
`Object.values()` return the values of properties in an object by iterating over each property according to the same semantics of `for..in`

> The traversal order, as of modern ECMAScript specification, is well-defined and consistent across implementations. Within each component of the prototype chain, all non-negative integer keys (those that can be array indices) will be traversed first in ascending order by value, **then other string keys in ascending chronological order of property creation**.

This code is fragile. First, if the tag objects are created differently, the order of the key and the value properties would change. Second, if another property is added to the tag object (`Tag` is just an interface, after all), you are going to join more than two components. I would prefer if you built the tuples by directly using the key and the value properties.

Moreover, looking at the corresponding PR in snyk-iac-test, the separator between keys and value is supposed to be a `=`. I'm fine with using `:` instead, since we don't process the tags in snyk-iac-test yet.

Sorry for being a nuisance!

2022-08-05 07:20 UTC, ipapast commented on src/lib/iac/test/v2/scan/index.ts
> +      return Object.values(tag).join(':');
we chatted on slack, pushed new commit

2022-08-05 07:47 UTC, francescomari approved these changes

2022-08-05 08:11 UTC, merged