fix: support unmanaged for ide plugins
snyk/cli pull request #4181
Opened 2022-10-30 21:00 UTC by dagrest

- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?

Add Test Support for IDE plugins for C/C++

#### Where should the reviewer start?

https://docs.snyk.io/ide-tools

#### How should this be manually tested?

https://docs.snyk.io/ide-tools

#### What are the relevant tickets?

[C++ Test Support for IDE plugins TUN-347](https://snyksec.atlassian.net/browse/TUN-347)

2022-10-31 09:37 UTC, danielroymoore requested changes
See thread.

2022-10-31 09:38 UTC, danielroymoore commented on src/lib/ecosystems/unmanaged/utils.ts
>    return newObj;
see thread

2022-10-31 09:38 UTC, danielroymoore commented on src/lib/ecosystems/resolve-test-facts.ts
>      return converted;
see thread

2022-11-04 09:20 UTC, danielroymoore commented on test/jest/unit/lib/ecosystems/resolve-test-facts.spec.ts
> +//import * as utils from '../../../../../src/lib/ecosystems/unmanaged/utils.ts';
Remove commented out code.

2022-11-04 09:22 UTC, danielroymoore commented on src/lib/ecosystems/resolve-test-facts.ts
> -
nit: add line back in, unnecessary amendment when git blaming.

2022-11-04 09:24 UTC, danielroymoore commented on src/lib/ecosystems/resolve-test-facts.ts
> +            issueData.version = issuesMap[issuesDataKey].pkgVersion;
Do you not want to add a `?.` in for optional chaining like on line 199?

2022-11-04 09:26 UTC, danielroymoore commented on src/lib/snyk-test/legacy.ts
> +  upgradePath?: (string | boolean)[];
As the values are hardcoded as booleans in the implementation, should this not be `boolean[]`? Is there scope in future for this not to be a hardcoded boolean value?

2022-11-07 07:20 UTC, dagrest commented on src/lib/snyk-test/legacy.ts
> +  upgradePath?: (string | boolean)[];
No, it will cause an error: Interface 'AnnotatedIssue' incorrectly extends interface 'IssueData'.
Types of property 'upgradePath' are incompatible.

2022-11-07 09:09 UTC, danielroymoore commented on src/lib/snyk-test/legacy.ts
> +  upgradePath?: (string | boolean)[];
Please confirm if the duplication needs addressing, as now the extending type won't need this property.

2022-11-08 12:07 UTC, Avishagp approved these changes

2022-11-08 13:49 UTC, merged