feat: yarn lock v2 support plus improvements
snyk/cli pull request #4222
Opened 2022-11-30 15:45 UTC by JamesPatrickGill

2022-12-01 08:24 UTC, admons requested changes

2022-12-01 08:24 UTC, admons commented on src/lib/plugins/nodejs-plugin/index.ts
> +function isResDepGraph(depRes: PkgTree | DepGraph): boolean {
Use the following pattern and you won't have to cast after in your if block
```typescript
function isDepGraph(item: PkgTree | DepGraph): item is DepGraph {
  return 'rootPkg' in item;
}

2022-12-01 08:24 UTC, admons commented on src/lib/plugins/nodejs-plugin/npm-lock-parser.ts
> +import { NodeLockfileVersion } from 'snyk-nodejs-lockfile-parser/dist/utils';
This should be imported on line 8

2022-12-01 08:24 UTC, admons commented on src/lib/plugins/nodejs-plugin/npm-lock-parser.ts
> +import { ProjectParseOptions } from 'snyk-nodejs-lockfile-parser/dist/dep-graph-builders/types';
If this is being used outside of the library, then it should be exported on it's `index.ts` file and imported here the same way on line 8

2022-12-01 08:24 UTC, admons commented on src/lib/plugins/nodejs-plugin/npm-lock-parser.ts
> +      return lockFileParser.parseYarnLockV2Project(
Weird that this is not an async method (in the library, I checked), maybe it should?
anyway if you're not changing it then ignore this comment

2022-12-01 09:11 UTC, JamesPatrickGill commented on src/lib/plugins/nodejs-plugin/npm-lock-parser.ts
> +      return lockFileParser.parseYarnLockV2Project(
We would force the function to be async, wonder where we could do this

2022-12-19 08:22 UTC, admons requested changes

2022-12-19 08:22 UTC, admons commented on src/lib/plugins/nodejs-plugin/index.ts
> +        (depRes as DepGraph)?.pkgManager.version,
```depRes.pkgManager.version```

2022-12-19 08:22 UTC, admons commented on src/lib/plugins/nodejs-plugin/index.ts
> +        (depRes as PkgTree)?.meta?.lockfileVersion,
```depRes.meta?.lockfileVersion```

2022-12-19 08:22 UTC, admons commented on src/lib/plugins/nodejs-plugin/npm-lock-parser.ts
> +  const strictOutOfSync = options.strictOutOfSync !== false;
What if this is null/undefined?

2022-12-20 12:53 UTC, admons approved these changes

2022-12-20 12:53 UTC, admons commented on src/lib/plugins/nodejs-plugin/index.ts
> +      analytics.add('lockfileVersion', depRes?.pkgManager.version);
Remove question mark

2022-12-20 12:53 UTC, admons commented on src/lib/plugins/nodejs-plugin/index.ts
> +      analytics.add('lockfileVersion', depRes?.meta?.lockfileVersion);
Remove question marks

2022-12-20 14:03 UTC, PeterSchafer reviewed
Suggestion: As you have added new logic and control flows, it would be important to add new tests for it. From the description, I would assume to find at least one additional acceptance test that uses a yarn v2 file. Unit tests would be great too.

2022-12-20 15:39 UTC, PeterSchafer approved these changes
As discussed with @JamesPatrickGill, adding additional tests will be done in a separate task. Approving to unblock.

2022-12-20 16:34 UTC, merged