chore: release golang cli on linux
snyk/cli pull request #4255
Opened 2022-12-21 11:11 UTC by Avishagp

Release golang CLI on linux.
[JIRA ticket](https://snyksec.atlassian.net/browse/HMMR-567)

2022-12-21 11:32 UTC, PeterSchafer commented on .circleci/config.yml
> +            - v2 / Sign (linux/amd64)
Question: I think this should be "Build (linux/amd64)"

2022-12-21 11:34 UTC, PeterSchafer commented on .circleci/config.yml
> +            - v2 / Rename macos/amd64 artifact
Question: why is this requiring "v2 / Rename macos/amd64 artifact"? Shouldn't it be linux?

2022-12-21 11:43 UTC, PeterSchafer requested changes
Unfortunately the build doesn't run, please see my comments on how to fix it.

2022-12-21 12:13 UTC, Avishagp commented on .circleci/config.yml
> +            - v2 / Rename macos/amd64 artifact
My bad!

2022-12-21 12:15 UTC, Avishagp commented on .circleci/config.yml
> +            - v2 / Sign (linux/amd64)
I used the same logic from `v2-rename-windows` and `v2-rename-macos`, both require signing before renaming. The logic is sign -> rename -> build. Does that make sense?

2022-12-21 13:57 UTC, PeterSchafer commented on .circleci/config.yml
> +            - v2 / Sign (linux/amd64)
In general that would be right, but linux artifacts don't get signed right now. 

If you look at the build log https://app.circleci.com/pipelines/github/snyk/cli/16176, you can see that this unknown job is the problem of your build.

You can also look at your changes here: https://github.com/snyk/cli/pull/4255/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47L1087 the prerequisite for the tests was "build" not "sign". So this should also be the prerequisite for the "rename".

I hope this helps.

2022-12-21 14:05 UTC, Avishagp commented on .circleci/config.yml
> +            - v2 / Sign (linux/amd64)
I'm sorry! thanks for explaining that

2022-12-21 15:00 UTC, PeterSchafer commented
Please also take rename/replace "snyk_linux_arm64"

2022-12-22 13:31 UTC, PeterSchafer approved these changes

2022-12-22 14:16 UTC, merged