feat: add report upload to code test [ZEN-494]
snyk/cli pull request #4422
Opened 2023-02-17 09:03 UTC by patricia-v

- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?

- Adds the report upload/ignores feature to the CLI
- Adds tests for:
  - reportResults in Code Test results
  - ignored issues through `suppressions` in sarif

#### Any background context you want to provide?

 - [CLI Uploads Feature Plan](https://www.notion.so/snyk/Snyk-Code-Publish-CLI-results-to-the-web-UI-7b48a23e44634c60a5063d2eb8b6c528)
 - [CLI Ignores Feature Plan](https://www.notion.so/snyk/Snyk-Code-CLI-Ignore-support-ae5eb72f6af940e087e801ade11154c9)

#### What are the relevant tickets?

 - [ZEN-494](https://snyksec.atlassian.net/browse/ZEN-494)

#### TODO ⚠️ 

- [ ] Bump code-client version to latest once [code-client#170](https://github.com/snyk/code-client/pull/170) has been merged

2023-02-17 10:26 UTC, michelkaporin commented on src/lib/plugins/sast/analysis.ts
> +    const ignored = (result.suppressions?.length ?? 0) > 0;
Is this redundant with the `filterIgnoredSecurityRules` below now?

2023-02-17 10:26 UTC, michelkaporin commented on src/lib/plugins/sast/analysis.ts
> +    analysisResults: codeAnalysis.analysisResults as AnalysisResultSarif,
Why casting when you can pass the right type from `getCodeAnalysis`?

2023-02-17 10:26 UTC, michelkaporin commented on test/jest/unit/snyk-code/snyk-code-test.spec.ts
> +    if (!sarifWithoutIgnores) return;
Returning here will likely cause the test to succeed when mocked result is changed - is this intended?

2023-02-17 10:26 UTC, michelkaporin commented on test/jest/unit/snyk-code/snyk-code-test.spec.ts
> +    if (!sarifWithIgnores) return;
Returning here will likely cause the test to succeed when mocked result is changed - is this intended?

2023-02-17 10:28 UTC, strassl-snyk requested changes
q: Same as for the code-client PR - we have made triple-sure that this will not affect existing functionality?

2023-02-17 10:28 UTC, strassl-snyk commented on src/lib/plugins/sast/format/output-format.ts
> +        if (res.fingerprints?.['identity']) {
q: I assume this won't show up in regular scans as `identity` is not set?

2023-02-17 10:28 UTC, strassl-snyk commented on src/lib/policy/find-and-load-policy.ts
> +  scanType: SupportedPackageManagers | 'docker' | 'iac' | 'cpp' | 'code',
q: What does this change do?

2023-02-17 10:28 UTC, strassl-snyk commented on test/fixtures/sast/sample-analyze-folders-with-report-and-ignores-response.json
> +    "sessionToken": "912D0461-5CCD-417B-8073-1305D1D896C2",
q: I assume that is sanitized data?

2023-02-17 10:28 UTC, strassl-snyk commented on test/jest/unit/snyk-code/snyk-code-test.spec.ts
> +    if (!sarifWithoutIgnores) return;
enh: We should really, really be failing the test if this happens. Silently early-exiting tests is a terrible practice and a good way to get silently failing tests. See also below.

2023-02-17 10:28 UTC, strassl-snyk commented on test/jest/unit/snyk-code/snyk-code-test.spec.ts
> +      reportOptions: {
req: This shouldn't be necessary as code-client should be backward compatible.

2023-02-17 11:41 UTC, novalex commented on src/lib/plugins/sast/format/output-format.ts
> +        if (res.fingerprints?.['identity']) {
Correct.

2023-02-17 11:43 UTC, patricia-v commented on src/lib/policy/find-and-load-policy.ts
> +  scanType: SupportedPackageManagers | 'docker' | 'iac' | 'cpp' | 'code',
Was not needed, removed

2023-02-17 11:44 UTC, Avishagp approved these changes

2023-02-17 11:46 UTC, patricia-v commented on test/fixtures/sast/sample-analyze-folders-with-report-and-ignores-response.json
> +    "sessionToken": "912D0461-5CCD-417B-8073-1305D1D896C2",
This file is exactly the same as `test/fixtures/sast/sample-analyze-folders-response.json` that we've had for quite a while, I just added the `suppressions` for the ignores. So I'm assuming yes

2023-02-17 11:49 UTC, patricia-v commented on src/lib/plugins/sast/analysis.ts
> +    analysisResults: codeAnalysis.analysisResults as AnalysisResultSarif,
I don't think there was a particular reason in this case, was more of a safeguard

@novalex do you remember if there was a reason for this at the time?

2023-02-17 12:05 UTC, patricia-v commented on test/jest/unit/snyk-code/snyk-code-test.spec.ts
> +      reportOptions: {
So you mean we should optionally send the `reportOptions` [in the analysis here](https://github.com/snyk/cli/pull/4422/files#diff-fc7edfb2a4c95c09bd721194b8c3e5f3775226c91c4ca0270e42d02046021140R103) and do something like the below?

```
...(options.report && {reportOptions: {
  enabled: options.report ?? false,
  projectName: options['project-name'],
  targetRef: options['target-reference'],
}}),
```

2023-02-17 12:52 UTC, patricia-v commented on test/jest/unit/snyk-code/snyk-code-test.spec.ts
> +      reportOptions: {
The changes I proposed above would be exactly that: only when `--report` is present, we send the `reportOptions` to `code-client` 😁

2023-02-17 12:53 UTC, strassl-snyk commented on test/jest/unit/snyk-code/snyk-code-test.spec.ts
> +      reportOptions: {
Yes, I was agreeing but trying to be explicit about it, so we catch any misunderstanding :D

2023-02-17 15:14 UTC, novalex commented on src/lib/plugins/sast/analysis.ts
> +    analysisResults: codeAnalysis.analysisResults as AnalysisResultSarif,
It's because in `FileAnalysis` the analysis results can be of type legacy or Sarif. For our use-cases we only use the Sarif type, but that's what the `code-client` lib returns. But fair point, it can be returned as the Sarif type from `getCodeAnalysis` and avoid casting that way.

2023-02-17 16:04 UTC, strassl-snyk commented on src/lib/plugins/sast/analysis.ts
> +    // TODO: move this out of here - it doesn't belong here and it's a hacky way to do it
We could apply the filtering further up in the stack outside `getSecurityResultsOnly` - I only put it there because it was the easiest place to put it, not the best.

2023-02-17 16:07 UTC, patricia-v commented on src/lib/plugins/sast/analysis.ts
> +    // TODO: move this out of here - it doesn't belong here and it's a hacky way to do it
Sounds promising, I'll give it a go 🤞

2023-02-20 11:55 UTC, strassl-snyk approved these changes

2023-02-20 11:55 UTC, strassl-snyk commented on src/lib/plugins/sast/analysis.ts
> +  if (options.report) {
q: We originally had this after `praseSecurityRules`, right? Does the order matter?

2023-02-20 12:04 UTC, patricia-v commented on src/lib/plugins/sast/analysis.ts
> +  if (options.report) {
It shouldn't matter, but to be safe I switched them again

2023-02-20 13:10 UTC, novalex commented on src/lib/plugins/sast/analysis.ts
> +    analysisResults: codeAnalysis.analysisResults as AnalysisResultSarif,
Unfortunately TS doesn't seem to figure out the results should be of type Sarif after we do the `result?.analysisResults.type !== 'sarif'` check and early return, so an explicit typecast is still needed.

2023-02-20 13:10 UTC, novalex submitted a review, later dismissed

2023-02-20 13:20 UTC, michelkaporin commented on src/lib/plugins/sast/analysis.ts
> +    analysisResults: codeAnalysis.analysisResults as AnalysisResultSarif,
Have you tried using [type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards)?

2023-02-20 13:22 UTC, michelkaporin submitted a review, later dismissed

2023-02-20 15:49 UTC, strassl-snyk submitted a review, later dismissed

2023-02-20 18:13 UTC, novalex commented on src/lib/plugins/sast/analysis.ts
> +    analysisResults: codeAnalysis.analysisResults as AnalysisResultSarif,
Yes but they're not helping readability and since we know the type will be Sarif I opted to just cast from inside the `getCodeAnalysis` function and let TS infer the correct type.

2023-02-20 18:14 UTC, novalex approved these changes

2023-02-21 07:37 UTC, michelkaporin approved these changes

2023-02-21 08:22 UTC, merged