fix: remove feature flag used to toggle old and new unmanaged service
snyk/cli pull request #4598
Opened 2023-05-11 14:07 UTC by dekelund

- [X] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?

Removes check of unused feature flag to decide which endpoint to use for tests of unmanaged source code.

- Removes support for USE_UNMANAGED_DEPS environment variable
- Removes support for snykNewUnmanagedTest feature flag

#### How should this be manually tested?

0. Use `snyk test --unmanaged` with an installation that has not been authenticated
1. Verify that the user receives a human readable reply, informing the user it's not authenticated
2. Run `snyk auth` to authenticate
3. Test the build with an unmanaged project, with following command `snyk test --unmanaged`
4. Verify the output correspond to the expected output

2023-05-11 14:47 UTC, aron approved these changes
Looks good, glad to see the improvement in error messaging for un-authenticated requests too 👍

2023-05-11 14:47 UTC, aron commented on src/lib/request/promise.ts
> +          error: error,
I'm not sure how this rejected object is used across the codebase. If it's output directly could this change leak internal error messages externally? @snyk/hammerhead will hopefully be able to provide some guidance.

Otherwise we could just pass a new error to the AuthFailedError constructor.

2023-05-11 15:00 UTC, Avishagp commented on src/lib/request/promise.ts
> +          error: error,
Agree with @aron, this change could be risky and I would refrain from making it.

2023-05-11 15:00 UTC, Avishagp requested changes
Please change `src/lib/request/promise.ts`

2023-05-11 15:27 UTC, dekelund commented on src/lib/request/promise.ts
> +          error: error,
It seems like it's expected from the  rest of the code base, if I don't do it it will end up with another error later. I fully understand that it might be dangerous, due to the language (in combination with the design).

I will look into it tomorrow and see what I can do to eliminate the risk.

2023-05-11 15:43 UTC, aron commented on src/lib/ecosystems/resolve-test-facts.ts
> +      throw AuthFailedError(error.error, error.code);
Based on the feedback earlier, I'd suggest just passing in a new error here to satisfy the wrapper. There's not much additional information we'd need for a 401/403 error that we don't already have from the request.

```suggestion
      throw AuthFailedError(new Error("Unauthorized request to unmanaged service"), error.code);
```

2023-05-12 11:23 UTC, dekelund commented on src/lib/ecosystems/resolve-test-facts.ts
> +      throw AuthFailedError(error.error, error.code);
AuthFailedError requires a string, so I will use a similar approach without the `NewError` call.

2023-05-12 13:21 UTC, Avishagp approved these changes

2023-05-12 14:07 UTC, merged