feat: stage unmanaged depgraph-endpoints
snyk/cli pull request #4811
Opened 2023-08-25 13:43 UTC by dekelund

- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?

THIS IS A DRAFT, PLEASE DON'T MERGE

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots

#### Additional questions

2023-09-01 09:24 UTC, dekelund commented
Looks like "update branch against master/main" in github is not compliant with our rules:

```
"[Merge branch 'master' into feat/stage-unmanaged-depgraphs-endpoints](https://api.github.com/repos/snyk/cli/git/commits/bd7a0ec672957772179d327faeaf67800c3901cc)" is not using a valid commit message format. For commit guidelines, see: [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md#creating-commits).
```

2023-09-01 09:36 UTC, darscan commented on package.json
> +    "snyk-cpp-plugin": "^2.24.0",
Please pin to an explicit version - the CLI is deployed as a unit, and we need to make sure a given CLI version always uses the same plugin versions.

2023-09-01 09:44 UTC, darscan requested changes
`snyk-cpp-plugin` needs to be pinned at a concrete version.

2023-09-01 12:54 UTC, dekelund commented on package.json
> +    "snyk-cpp-plugin": "^2.24.0",
My mistake, not intentional

2023-09-04 06:51 UTC, bastiandoetsch commented
Hey @dekelund , would you please add acceptance tests for the testing laid our in the PR description?

2023-09-04 11:20 UTC, bastiandoetsch approved these changes

2023-09-04 19:49 UTC, darscan approved these changes

2023-09-04 21:55 UTC, merged