feat: use gw routing for code
snyk/cli pull request #4857
Opened 2023-09-13 13:25 UTC by Noa-Savransky

- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots

#### Additional questions

2023-09-18 07:06 UTC, pkey requested changes
I guess this should also go to the ownership of @snyk/pulsar since we switched `deeproxy` ownership.

2023-10-11 08:47 UTC, PeterSchafer approved these changes

2023-10-11 09:04 UTC, strassl-snyk approved these changes

2023-10-12 07:05 UTC, pkey approved these changes

2023-10-16 14:13 UTC, merged