fix: add percent-encoded plus sign in purl version tests
snyk/cli pull request #4939
Opened 2023-11-20 17:15 UTC by ahmed-agabani-snyk

## What does this PR do?

Adds percent-encoded plus sign in purl version tests

2023-11-20 17:30 UTC, cat2608 approved these changes

2023-11-21 08:37 UTC, bastiandoetsch requested changes
Hey @ahmed-agabani-snyk, please use the PR template.

2023-11-21 10:29 UTC, ahmed-agabani-snyk commented
> Hey @ahmed-agabani-snyk, would you please use the PR template? Thanks a lot!

Hi @bastiandoetsch, I've updated the pull request description to use the pull request template.

2023-11-21 10:30 UTC, bastiandoetsch approved these changes
Thank you so much!

2023-11-21 10:31 UTC, merged