feat(#2439): populate CVSS scores in SARIF files
snyk/cli pull request #5014
Opened 2024-01-19 21:33 UTC by schottsfired

Addresses #2439.

Adds `security-severity` to open source and container SARIF output.

2024-01-22 08:58 UTC, thisislawatts approved these changes

2024-01-22 14:28 UTC, cmars approved these changes
LGTM with a request for code comments

2024-01-22 14:28 UTC, cmars commented on src/lib/formatters/open-source-sarif-output.ts
> +          "security-severity": vuln.cvssScore,
It might be worth commenting which vendors these fields are intended for. TIL AWS uses `cvssv3_baseScore`, Github uses `security-severity`.

Would have made the intent here a lot clearer (I was wondering, why are we copying the CVSS with a different name?)

2024-01-22 14:38 UTC, cmars requested changes
Needs further discussion with @snyk/cli

2024-01-22 16:10 UTC, schottsfired commented on src/lib/formatters/open-source-sarif-output.ts
> +          "security-severity": vuln.cvssScore,
Couldn't agree more, I thought of that as well after filing. Will add.

2024-01-22 17:26 UTC, cmars approved these changes

2024-02-14 10:48 UTC, ipanagiotidis commented
Hello, what is the status of this PR? We are using both Snyk and Trivy for scans in GIthub Actions and pushing them to Security Dashboard.

The problem with Snyk is that is doesn't report security-severity. This means that all reports by Snyk get a warning or note severity instead of medium or low, which hides them in later pages of github advanced security.

Example: Snyk and Trivy report the same vulnerability but Trivy reports it as Low severity and Snyk as Medium severity. In Github Security Dashboard, Trivy will get correct severity of Low, but Snyk gets a wrong severity of "warning", and it is places **below** the severity of Trivy,

2024-02-20 20:53 UTC, schottsfired commented
Hi @ipanagiotidis, apologies for the delay, I've been AFK for a few weeks due to a knee surgery and just returned today. I intend to address the comments in this PR, then move the code to a new branch to prepare for merge. Hang tight! 🙏

2024-03-04 14:34 UTC, merged

2024-03-05 10:32 UTC, pgrabowski commented
Unfortunately this broke import of Sarif files to GitHub as expect quoted string for security-severity as in doc https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#reportingdescriptor-object

2024-03-21 22:56 UTC, schottsfired commented
Darn! Sorry about that @pgrabowski - I overlooked "**A string** representing a score" 🤦‍♂️ 

Thanks so much @thisislawatts for the quick fix 🙏