feat: parse workflow data to determine errors
snyk/cli pull request #5157
Opened 2024-04-10 07:36 UTC by thisislawatts

## Pull Request Submission

Please check the boxes once done.

The pull request must:

- **Reviewer Documentation**
    - [ ] follow [CONTRIBUTING](https://github.com/snyk/cli/blob/main/CONTRIBUTING.md) rules
    - [ ] be accompanied by a detailed description of the changes
    - [ ] contain a risk assessment of the change (Low | Medium | High) with regards to breaking existing functionality. A change e.g. of an underlying language plugin can completely break the functionality for that language, but appearing as only a version change in the dependencies.
    - [ ] highlight breaking API if applicable
    - [ ] contain a link to the automatic tests that cover the updated functionality.
    - [ ] contain testing instructions in case that the reviewer wants to manual verify as well, to add to the manual testing done by the author.
    - [ ] link to the link to the PR for the User-facing documentation
- **User facing Documentation**
    - [ ] update any relevant documentation in gitbook by submitting a gitbook PR, and including the PR link here
    - [ ] ensure that the message of the final single commit is descriptive and prefixed with either `feat:` or `fix:` , others might be used in rare occasions as well, if there is no need to document the changes in the release notes. The changes or fixes should be described in detail in the commit message for the changelog & release notes.
- **Testing**
    - [ ] Changes, removals and additions to functionality must be covered by acceptance / integration tests or smoke tests - either already existing ones, or new ones, created by the author of the PR.

## Pull Request Review

All pull requests must undergo a thorough review process before being merged. 
The review process of the code PR should include code review, testing, and any necessary feedback or revisions. 
Pull request reviews of functionality developed in other teams only review the given documentation and test reports. 

Manual testing will not be performed by the reviewing team, and is the responsibility of the author of the PR.

For Node projects: It’s important to make sure changes in `package.json` are also affecting `package-lock.json` correctly.

****************************If a dependency is not necessary, don’t add it.**************************** 

When adding a new package as a dependency, make sure that the change is absolutely necessary. We would like to refrain from adding new dependencies when possible.
Documentation PRs in gitbook are reviewed by Snyk's content team. They will also advise on the best phrasing and structuring if needed.

## Pull Request Approval

Once a pull request has been reviewed and all necessary revisions have been made, it is approved for merging into 
the main codebase. The merging of the code PR is performed by the code owners, the merging of the documentation PR 
by our content writers.

## What does this PR do?

Allows exit code to be affected by data payloads generated as part of workflows. 

## Where should the reviewer start?

## How should this be manually tested?

## Any background context you want to provide?

## What are the relevant tickets?

2024-04-10 15:17 UTC, thisislawatts commented on cliv2/cmd/cliv2/main.go
> +			}
**todo:** Update this to use exported type now available in go-application-framework

2024-04-10 15:21 UTC, thisislawatts commented on cliv2/cmd/cliv2/main_test.go
>  func Test_setTimeout(t *testing.T) {
These tests are fairly low level at the moment. I would like to introduce a "closed" box one but wasn't sure how to mock a workflow that would return the appropriate payload. I am open to suggestions :)

2024-04-12 07:39 UTC, PeterSchafer commented on cliv2/cmd/cliv2/main.go
> +					return fmt.Errorf("vulnerabilities found")
Suggestion: Let's introduce a custom error Type instead of relying on string comparison to find the error. For example an error that can hold the exit code, so that it can be easily used to return multiple error codes.

2024-04-12 07:43 UTC, PeterSchafer commented on cliv2/cmd/cliv2/main.go
> +				return fmt.Errorf("invalid payload type: %T", data[i].GetPayload())
Nitpick: For error messages to be a bit more self explanatory maybe mention what failed and then the why.

2024-04-12 07:44 UTC, PeterSchafer commented on cliv2/cmd/cliv2/main.go
> +				return fmt.Errorf("failed to unmarshal json: %w", err)
Nitpick: For error messages to be a bit more self explanatory maybe mention what failed and then the why.

2024-04-12 11:27 UTC, thisislawatts commented on cliv2/cmd/cliv2/main.go
> +					return fmt.Errorf("vulnerabilities found")
Addressed in 2fadcff683ac0658cc4f86b223f72855f4179e44

2024-04-12 16:34 UTC, PeterSchafer commented on cliv2/cmd/cliv2/main.go
> +	_ "github.com/snyk/go-application-framework/pkg/networking/fips_enable"
Issue: This import needs to be separated.

2024-04-12 16:36 UTC, PeterSchafer commented on cliv2/cmd/cliv2/main.go
> +			}
Suggestion: I think this comment is still valid and the data structure should be re-used instead of redefined.

2024-04-12 16:38 UTC, PeterSchafer commented on cliv2/internal/cliv2/cliv2.go
> +		if strErr == "vulnerabilities found" {
Question: Isn't this obsolete now with the new ErrorWithExitCode?

2024-04-12 16:42 UTC, PeterSchafer commented on cliv2/cmd/cliv2/main_test.go
> +		data := workflow.NewData(workflowIdentifier, "application/json; type=snyk-test-summary", []byte(`{"results": [{"severity": "critical", "total": 99, "open": 97, "ignored": 2}]}`))
Suggestion: specifying the json representation like this will make it difficult to maintain these tests, how about using the struct and marshalling it?

2024-04-12 18:19 UTC, thisislawatts commented on cliv2/cmd/cliv2/main.go
> +	_ "github.com/snyk/go-application-framework/pkg/networking/fips_enable"
Flipping editor 🙄

2024-04-12 18:21 UTC, thisislawatts commented on cliv2/cmd/cliv2/main.go
> +	_ "github.com/snyk/go-application-framework/pkg/networking/fips_enable"
Addressed in 3848beda85bdb49b9c6ed95ad9ec82fa2c1a0fb0

2024-04-12 18:22 UTC, thisislawatts commented on cliv2/internal/cliv2/cliv2.go
> +		if strErr == "vulnerabilities found" {
🧹 0d838599df55b5e39f8b5de66c87846010f46135

2024-04-12 19:55 UTC, thisislawatts commented on cliv2/cmd/cliv2/main_test.go
> +		data := workflow.NewData(workflowIdentifier, "application/json; type=snyk-test-summary", []byte(`{"results": [{"severity": "critical", "total": 99, "open": 97, "ignored": 2}]}`))
Fixed in: https://github.com/snyk/cli/pull/5157/commits/30e7531b2c13ff2967d396878a8340f8ef53484a

2024-04-15 12:37 UTC, thisislawatts commented on cliv2/cmd/cliv2/main_test.go
> +		config := configuration.New()
Updated in: https://github.com/snyk/cli/pull/5157/commits/d402468ca9997f2461f66c5be7b10141b89fd04c

2024-04-15 15:23 UTC, PeterSchafer commented on cliv2/cmd/cliv2/main.go
> +	// TODO: Add Tests
Question: can this todo be removed now?

2024-04-15 15:27 UTC, PeterSchafer commented on cliv2/cmd/cliv2/main_test.go
> +	t.Run("workflow without errors", func(t *testing.T) {
Question: This test case is the same as the one above. Is this on purpose?

2024-04-15 16:25 UTC, PeterSchafer requested changes
Please address the open comments.

2024-04-15 17:36 UTC, thisislawatts commented on cliv2/cmd/cliv2/main_test.go
> +	t.Run("workflow without errors", func(t *testing.T) {
Addressed in: https://github.com/snyk/cli/pull/5157/commits/9b131a8d2e1aae6c975d751d9486f9c88e02f480

2024-04-15 17:36 UTC, thisislawatts commented on cliv2/cmd/cliv2/main.go
> +	// TODO: Add Tests
Addressed in https://github.com/snyk/cli/pull/5157/commits/9b131a8d2e1aae6c975d751d9486f9c88e02f480

2024-04-15 18:59 UTC, PeterSchafer approved these changes

2024-04-15 19:00 UTC, merged