feat(instrumentation): add trace level logging of request CLI-325
snyk/cli pull request #5244
Opened 2024-05-17 14:56 UTC by mgyorke

## Pull Request Submission

Please check the boxes once done.

The pull request must:

- **Reviewer Documentation**
    - [ ] follow [CONTRIBUTING](https://github.com/snyk/cli/blob/main/CONTRIBUTING.md) rules
    - [ ] be accompanied by a detailed description of the changes
    - [ ] contain a risk assessment of the change (Low | Medium | High) with regards to breaking existing functionality. A change e.g. of an underlying language plugin can completely break the functionality for that language, but appearing as only a version change in the dependencies.
    - [ ] highlight breaking API if applicable
    - [ ] contain a link to the automatic tests that cover the updated functionality.
    - [ ] contain testing instructions in case that the reviewer wants to manual verify as well, to add to the manual testing done by the author.
    - [ ] link to the link to the PR for the User-facing documentation
- **User facing Documentation**
    - [ ] update any relevant documentation in gitbook by submitting a gitbook PR, and including the PR link here
    - [ ] ensure that the message of the final single commit is descriptive and prefixed with either `feat:` or `fix:` , others might be used in rare occasions as well, if there is no need to document the changes in the release notes. The changes or fixes should be described in detail in the commit message for the changelog & release notes.
- **Testing**
    - [ ] Changes, removals and additions to functionality must be covered by acceptance / integration tests or smoke tests - either already existing ones, or new ones, created by the author of the PR.

## Pull Request Review

All pull requests must undergo a thorough review process before being merged. 
The review process of the code PR should include code review, testing, and any necessary feedback or revisions. 
Pull request reviews of functionality developed in other teams only review the given documentation and test reports. 

Manual testing will not be performed by the reviewing team, and is the responsibility of the author of the PR.

For Node projects: It’s important to make sure changes in `package.json` are also affecting `package-lock.json` correctly.

****************************If a dependency is not necessary, don’t add it.**************************** 

When adding a new package as a dependency, make sure that the change is absolutely necessary. We would like to refrain from adding new dependencies when possible.
Documentation PRs in gitbook are reviewed by Snyk's content team. They will also advise on the best phrasing and structuring if needed.

## Pull Request Approval

Once a pull request has been reviewed and all necessary revisions have been made, it is approved for merging into 
the main codebase. The merging of the code PR is performed by the code owners, the merging of the documentation PR 
by our content writers.

## What does this PR do?
This PR adds logging of the request at trace level.

## Where should the reviewer start?

## How should this be manually tested?

## Any background context you want to provide?
It's important that this PR is merged with a GAF bump after [this PR](https://github.com/snyk/go-application-framework/pull/178) is merged.

## What are the relevant tickets?

## Screenshots

## Additional questions

2024-05-17 16:55 UTC, PeterSchafer commented on cliv2/internal/proxy/proxy.go
> +	p.DebugLogger = log.New(&gafUtils.ToZeroLogDebug{Logger: debugLogger}, "", 0)
Suggestion: try to use DebugLogger as zerolog logger, this will be possible every except of two places. For these places you could add an additional property here.

2024-05-17 17:00 UTC, PeterSchafer requested changes

2024-05-17 17:00 UTC, PeterSchafer commented on cliv2/internal/proxy/proxy.go
> +	zerologLogger := zerolog.New(os.Stderr).With().Timestamp().Logger()
Issue: you need to use the centrally supplied logger! It is not correct to create a new one here.

2024-05-17 17:00 UTC, PeterSchafer commented on cliv2/internal/proxy/proxy_test.go
> +var debugLogger = zerolog.New(zerolog.ConsoleWriter{
Suggestion: zerolog has a default logger which could be used here

2024-05-17 17:00 UTC, PeterSchafer commented on cliv2/internal/proxy/proxy_test.go
> +	loggerWrapper := log.New(&gafUtils.ToZeroLogDebug{Logger: &debugLogger}, "", 0)
Suggestion: I think you can just use a log.Logger here, no need to use the wrapper

2024-05-17 17:00 UTC, PeterSchafer commented on cliv2/pkg/basic_workflows/legacycli.go
> +	debugLogger := invocation.GetEnhancedLogger()
Suggestion: I would use both logger types from the context instead of creating a ToZeroLogDebug below. The logic is at one place and if we want to remove one day the log.Logger usage, it will be easier to find.

2024-05-17 17:01 UTC, PeterSchafer commented
This PR relies on changes on the go-application-framework but there are no changes to the go.mod. This means the changes will never build. please update to gaf link even if it is just a temporary commit hash, so that the CLI build can show issues.

2024-05-21 11:14 UTC, PeterSchafer commented on .circleci/config.yml
> +            npx tap -j 1 -C --timeout=1000 -R junit --reporter-file=tap-junit.xml
Suggestion: please remove this again

2024-05-21 11:15 UTC, PeterSchafer commented on cliv2/internal/proxy/proxy.go
> +		p.authenticator = httpauth.NewProxyAuthenticator(p.authMechanism, p.upstreamProxy, log.Default())
Issue: this needs to use a log.Logger that uses a writer to zerolog

2024-05-21 11:17 UTC, PeterSchafer commented on cliv2/internal/proxy/proxy.go
> +	certPEMBlock, keyPEMBlock, err := certs.MakeSelfSignedCert(certName, []string{}, log.Default())
Issue: this needs to use a log.Logger that uses a writer to zerolog ToZeroLogDebug! Otherwise, the log.Default logger doesn't respect the debug configuration and logger configuration that is centrally done.

Same as below!

2024-05-22 09:34 UTC, mgyorke commented on .circleci/config.yml
> +            npx tap -j 1 -C --timeout=1000 -R junit --reporter-file=tap-junit.xml
I reverted this and a few other changes done while debugging the pipeline issues.

2024-05-22 17:09 UTC, PeterSchafer requested changes
The logs now contain additional new lines, see screenshot. This is probably due to different behaviour of the logger functions.

<img width="591" alt="image" src="https://github.com/snyk/cli/assets/101886095/6263bea4-47f6-4278-8670-b28c452c9e6a">

2024-05-24 14:58 UTC, PeterSchafer approved these changes

2024-05-24 14:59 UTC, merged