fix: container monitor json output
snyk/cli pull request #5347
Opened 2024-06-26 23:36 UTC by cmars

`snyk container monitor --json` was writing separators between multiple depgraph test results in the output, resulting in an invalid JSON output which does not parse.

This fixes the output by using the same function used to process multiple open source results in the `snyk monitor` command.

---

## Pull Request Submission

Please check the boxes once done.

The pull request must:

- **Reviewer Documentation**
    - [ ] follow [CONTRIBUTING](https://github.com/snyk/cli/blob/main/CONTRIBUTING.md) rules
    - [ ] be accompanied by a detailed description of the changes
    - [ ] contain a risk assessment of the change (Low | Medium | High) with regards to breaking existing functionality. A change e.g. of an underlying language plugin can completely break the functionality for that language, but appearing as only a version change in the dependencies.
    - [ ] highlight breaking API if applicable
    - [ ] contain a link to the automatic tests that cover the updated functionality.
    - [ ] contain testing instructions in case that the reviewer wants to manual verify as well, to add to the manual testing done by the author.
    - [ ] link to the link to the PR for the User-facing documentation
- **User facing Documentation**
    - [ ] update any relevant documentation in gitbook by submitting a gitbook PR, and including the PR link here
    - [ ] ensure that the message of the final single commit is descriptive and prefixed with either `feat:` or `fix:` , others might be used in rare occasions as well, if there is no need to document the changes in the release notes. The changes or fixes should be described in detail in the commit message for the changelog & release notes.
- **Testing**
    - [ ] Changes, removals and additions to functionality must be covered by acceptance / integration tests or smoke tests - either already existing ones, or new ones, created by the author of the PR.

## Pull Request Review

All pull requests must undergo a thorough review process before being merged. 
The review process of the code PR should include code review, testing, and any necessary feedback or revisions. 
Pull request reviews of functionality developed in other teams only review the given documentation and test reports. 

Manual testing will not be performed by the reviewing team, and is the responsibility of the author of the PR.

For Node projects: It’s important to make sure changes in `package.json` are also affecting `package-lock.json` correctly.

****************************If a dependency is not necessary, don’t add it.**************************** 

When adding a new package as a dependency, make sure that the change is absolutely necessary. We would like to refrain from adding new dependencies when possible.
Documentation PRs in gitbook are reviewed by Snyk's content team. They will also advise on the best phrasing and structuring if needed.

## Pull Request Approval

Once a pull request has been reviewed and all necessary revisions have been made, it is approved for merging into 
the main codebase. The merging of the code PR is performed by the code owners, the merging of the documentation PR 
by our content writers.

## What does this PR do?

See top posting

## Where should the reviewer start?

## How should this be manually tested?

Build this branch (`make clean build`).

Run `snyk container monitor --json snyk/snyk:linux | tee output.json`.

`jq < output.json` should exit 0, parse JSON successfully.

## Any background context you want to provide?

## What are the relevant tickets?

CLI-315

## Screenshots

## Additional questions

2024-07-08 11:32 UTC, PeterSchafer commented
@cmars could you please add a User Journey test. In addition during the review we realized that the output seems to change more than just removing the separators. Could we add a tests that compares the output of `snyk container test --json` and `snyk container monitor --json`.

2024-07-08 13:03 UTC, PeterSchafer requested changes
Looking at the behaviour of `snyk test --json --all-projects` and `snyk monipr --json --all-projects` I think my previous comment shows an issue with the solution.

For now, the change here produces the same output when using `--json` with `snyk container test` and `snyk container monitor`. This is different to the behaviour of `snyk test` and `snyk monitor` with `--json`. 

Some information like the `manageUrl` is not available anymore after these changes.

2024-07-08 13:14 UTC, cmars commented
Thanks for raising this, as I think it will be important to clearly communicate the impact of the changes we introduce here (whichever way we decide).

AFAICT `snyk container monitor --json` output has been structured differently from `snyk container test --json`. Remediating that will likely constitute a breaking change, requiring a major version bump. I would suggest not doing that in this PR.

I'll do a comparison before & after illustrating the impact of changes here, so that we can make an informed decision on next steps. And add tests!

2024-07-09 13:24 UTC, PeterSchafer approved these changes

2024-07-09 14:49 UTC, sandor-trombitas approved these changes

2024-07-09 15:24 UTC, merged