feat(localfindings): add new filter workflow for local findings
snyk/cli pull request #5553
Opened 2024-10-25 11:36 UTC by sandor-trombitas

## Pull Request Submission Checklist
- [ ] Follows [CONTRIBUTING](https://github.com/snyk/cli/blob/main/CONTRIBUTING.md) guidelines
- [ ] Includes detailed description of changes
- [ ] Contains risk assessment (Low | Medium | High)
- [ ] Highlights breaking API changes (if applicable)
- [ ] Links to automated tests covering new functionality
- [ ] Includes manual testing instructions (if necessary)
- [ ] Updates relevant GitBook documentation (PR link: ___)

## What does this PR do?
- Bumps GAF to add a new filter workflow that filters a local findings model based on severity-threshold

## Where should the reviewer start?

## How should this be manually tested?

2024-10-25 12:17 UTC, j-luong commented on cliv2/cmd/cliv2/main.go
> -import _ "github.com/snyk/go-application-framework/pkg/networking/fips_enable"
question: considering the comment above this import, was moving it intentional?

2024-10-25 12:18 UTC, sandor-trombitas commented on cliv2/cmd/cliv2/main.go
> -import _ "github.com/snyk/go-application-framework/pkg/networking/fips_enable"
it was not 😱

2024-10-30 09:55 UTC, PeterSchafer commented on cliv2/go.sum
> +github.com/snyk/go-application-framework v0.0.0-20241025112937-37db20ab7d62 h1:YVJJnwISffl+LUcqOR2P9aCgEsa9DiZXfwGJnHvda1Q=
Seems like you will need to run `go mod tidy`

2024-11-01 15:30 UTC, thisislawatts requested changes

2024-11-01 15:30 UTC, thisislawatts commented on cliv2/cmd/cliv2/main_test.go
> +		assert.True(t, localFindingsFound)
**issue(blocking):** We want to add in an assertion that validates the data that is received after the filter workflow has run.

2024-11-06 10:47 UTC, merged